(function(g){var window=this;'use strict';var GSa=function(a,b){return g.Ae(a,b)},HSa=function(a,b){b=b instanceof g.Bf?b:g.Hf(b,/^data:image\//i.test(b));
a.src=g.Cf(b)},O6=function(a){g.Yj(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^g.Sa()).toString(36));
return a},P6=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.dk(a.u,b,c)},ISa=function(a){if(a===g.no)throw Error("ES6 Iteration protocol does NOT adjust control flow when StopIteration is thrown from callback helper functions. If your code relies on this behavior, consider throwing a different error and catching it to terminate iteration.");
throw a;},JSa=function(a){if(a instanceof g.lo)return a;
if("function"==typeof a.Lg)return a.Lg(!1);if(g.Ka(a)){var b=0,c=new g.lo;c.next=function(){for(;;){if(b>=a.length)return g.f2;if(b in a)return g.mo(a[b++]);b++}};
var d=c.next;c.zj=function(){return g.oo(d.call(c))};
return c}throw Error("Not implemented");},KSa=function(a,b,c){if(g.Ka(a))try{g.kc(a,b,c)}catch(e){ISa(e)}else for(a=JSa(a);;){var d=void 0;
try{d=a.zj()}catch(e){if(e===g.no)break;throw e;}try{b.call(c,d,void 0,a)}catch(e){ISa(e)}}},LSa=function(a,b){var c=[];
KSa(b,function(d){try{var e=g.Fr.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.Er(e)&&c.push(d)},a);
return c},MSa=function(a,b){LSa(a,b).forEach(function(c){g.Fr.prototype.remove.call(this,c)},a)},NSa=function(a){if(a.va){if(a.va.locationOverrideToken)return{locationOverrideToken:a.va.locationOverrideToken};
if(null!=a.va.latitudeE7&&null!=a.va.longitudeE7)return{latitudeE7:a.va.latitudeE7,longitudeE7:a.va.longitudeE7}}return null},OSa=function(a,b){g.Pb(a,b)||a.push(b)},Q6=function(a){var b=0,c;
for(c in a)b++;return b},PSa=function(a){try{return g.C.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},R6=function(a){if(g.C.JSON)try{return g.C.JSON.parse(a)}catch(b){}return PSa(a)},QSa=function(a,b,c,d){var e=new g.Qj(null,void 0);
a&&g.Rj(e,a);b&&g.Sj(e,b);c&&g.Tj(e,c);d&&(e.K=d);return e},S6=function(a,b){g.mv[a]=!0;
var c=g.kv();c&&c.publish.apply(c,arguments);g.mv[a]=!1},T6=function(a){this.name=this.id="";
this.clientName="UNKNOWN_INTERFACE";this.app="";this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.fr;this.model=this.brand="";this.year=0;this.chipset=this.osVersion=this.os="";this.mdxDialServerType="MDX_DIAL_SERVER_TYPE_UNKNOWN";a&&(this.id=a.id||a.name,this.name=a.name,this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=
a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",RSa(this,a.capabilities||""),SSa(this,a.experiments||""),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN",a=a.deviceInfo)&&(a=JSON.parse(a),this.brand=a.brand||"",this.model=a.model||"",this.year=a.year||0,this.os=a.os||"",
this.osVersion=a.osVersion||"",this.chipset=a.chipset||"",this.clientName=a.clientName?a.clientName.toUpperCase():"UNKNOWN_INTERFACE",this.mdxDialServerType=a.mdxDialServerType||"MDX_DIAL_SERVER_TYPE_UNKNOWN")},RSa=function(a,b){a.capabilities.clear();
g.No(b.split(","),g.Pa(GSa,TSa)).forEach(function(c){a.capabilities.add(c)})},SSa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},U6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||"";this.idType=a.screenIdType||"normal"},V6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},USa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid,screenIdType:a.idType}},VSa=function(a){return new U6(a)},WSa=function(a){return Array.isArray(a)?g.um(a,VSa):[]},W6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+((a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+",idType:"+a.idType+"}"):"null"},X6=function(a){return Array.isArray(a)?"["+g.um(a,W6).join(",")+"]":"null"},Y6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},XSa=function(a){return g.um(a,function(b){return{key:b.id,
name:b.name}})},Z6=function(a,b){return g.Mb(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},$6=function(a,b){return g.Mb(a,function(c){return V6(c,b)})},YSa=function(){var a=(0,g.Ky)();
a&&MSa(a,a.i.Lg(!0))},a7=function(){var a=g.Ny("yt-remote-connected-devices")||[];
g.hc(a);return a},ZSa=function(a){if(g.Qb(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return g.um(a,function(d,e){return 0==e?d:d.substring(c.length)})},$Sa=function(a){g.My("yt-remote-connected-devices",a,86400)},c7=function(){if(b7)return b7;
var a=g.Ny("yt-remote-device-id");a||(a=Y6(),g.My("yt-remote-device-id",a,31536E3));for(var b=a7(),c=1,d=a;g.Pb(b,d);)c++,d=a+"#"+c;return b7=d},d7=function(){var a=a7(),b=c7();
g.Pb(a,b);g.Py()&&g.jc(a,b);a=ZSa(a);if(g.Qb(a))try{g.Xt("remote_sid")}catch(c){}else try{g.Vt("remote_sid",a.join(","),-1)}catch(c){}},aTa=function(){return g.Ny("yt-remote-session-browser-channel")},bTa=function(){return g.Ny("yt-remote-local-screens")||[]},cTa=function(){g.My("yt-remote-lounge-token-expiration",!0,86400)},dTa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=g.um(bTa(),function(d){return d.loungeToken}),c=g.um(a,function(d){return d.loungeToken});
g.vm(c,function(d){return!g.Pb(b,d)})&&cTa();
g.My("yt-remote-local-screens",a,31536E3)},eTa=function(a,b){g.My("yt-remote-session-browser-channel",a);
g.My("yt-remote-session-screen-id",b);a=a7();b=c7();g.Pb(a,b)||a.push(b);$Sa(a);d7()},e7=function(a){a||(g.Oy("yt-remote-session-screen-id"),g.Oy("yt-remote-session-video-id"));
d7();a=a7();g.Ub(a,c7());$Sa(a)},fTa=function(){if(!f7){var a=g.Pr();
a&&(f7=new g.zr(a))}},gTa=function(){fTa();
return f7?!!f7.get("yt-remote-use-staging-server"):!1},g7=function(){var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);
return a?parseInt(a[1],10):0},hTa=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},iTa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},h7=function(a){a.length?jTa(a.shift(),function(){h7(a)}):i7()},kTa=function(a){return"chrome-extension://"+a+"/cast_sender.js"},jTa=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);g.Zk(d,g.nr(a));(document.head||document.documentElement).appendChild(d)},lTa=function(){var a=g7(),b=[];
if(1<a){var c=a-1;b.push("//www.gstatic.com/eureka/clank/"+a+"/cast_sender.js");b.push("//www.gstatic.com/eureka/clank/"+c+"/cast_sender.js")}return b},i7=function(){var a=iTa();
a&&a(!1,"No cast extension found")},j7=function(){if(mTa){var a=2,b=iTa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;jTa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",i7,c)}},nTa=function(){j7();
var a=lTa();a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},pTa=function(){j7();
var a=lTa();a.push.apply(a,g.v(oTa.map(kTa)));a.push("//www.gstatic.com/eureka/clank/cast_sender.js");h7(a)},k7=function(a,b,c){g.H.call(this);
this.I=null!=c?(0,g.E)(a,c):a;this.Sf=b;this.D=(0,g.E)(this.wQ,this);this.i=!1;this.u=0;this.B=this.Mb=null;this.C=[]},l7=function(a,b,c){g.H.call(this);
this.C=null!=c?a.bind(c):a;this.Sf=b;this.B=null;this.i=!1;this.u=0;this.Mb=null},m7=function(a){a.Mb=g.Ah(function(){a.Mb=null;
a.i&&!a.u&&(a.i=!1,m7(a))},a.Sf);
var b=a.B;a.B=null;a.C.apply(null,b)},n7=function(){},o7=function(a,b){if("function"!==typeof a)throw Error("Fn must not be null and must be a function");
return g.C.setTimeout(function(){a()},b)},q7=function(a){p7.dispatchEvent(new qTa(p7,a))},qTa=function(a,b){g.ie.call(this,"statevent",a);
this.stat=b},r7=function(a,b,c,d){this.i=a;
this.B=b;this.S=c;this.K=d||1;this.u=45E3;this.C=new g.ek(this);this.I=new g.zh;this.I.setInterval(250)},sTa=function(a,b,c){a.It=1;
a.Um=O6(b.clone());a.xq=c;a.D=!0;rTa(a,null)},s7=function(a,b,c,d,e){a.It=1;
a.Um=O6(b.clone());a.xq=null;a.D=c;e&&(a.NN=!1);rTa(a,d)},rTa=function(a,b){a.ut=Date.now();
t7(a);a.Eo=a.Um.clone();P6(a.Eo,"t",a.K);a.xB=0;a.Lf=a.i.pD(a.i.nx()?b:null);0<a.kC&&(a.LA=new l7((0,g.E)(a.RO,a,a.Lf),a.kC));a.C.Ra(a.Lf,"readystatechange",a.xQ);b=a.Yo?g.Je(a.Yo):{};a.xq?(a.vB="POST",b["Content-Type"]="application/x-www-form-urlencoded",a.Lf.send(a.Eo,a.vB,a.xq,b)):(a.vB="GET",a.NN&&!g.Hg&&(b.Connection="close"),a.Lf.send(a.Eo,a.vB,null,b));a.i.Aj(1)},uTa=function(a,b){var c=a.xB,d=b.indexOf("\n",c);
if(-1==d)return u7;c=Number(b.substring(c,d));if(isNaN(c))return tTa;d+=1;if(d+c>b.length)return u7;b=b.substr(d,c);a.xB=d+c;return b},wTa=function(a,b){a.ut=Date.now();
t7(a);var c=b?window.location.hostname:"";a.Eo=a.Um.clone();g.Yj(a.Eo,"DOMAIN",c);g.Yj(a.Eo,"t",a.K);try{a.Qj=new ActiveXObject("htmlfile")}catch(m){v7(a);a.Om=7;q7(22);w7(a);return}var d="<html><body>";if(b){var e="";for(b=0;b<c.length;b++){var f=c.charAt(b);if("<"==f)f=e+"\\x3c";else if(">"==f)f=e+"\\x3e";else{if(f in x7)f=x7[f];else if(f in vTa)f=x7[f]=vTa[f];else{var h=f.charCodeAt(0);if(31<h&&127>h)var l=f;else{if(256>h){if(l="\\x",16>h||256<h)l+="0"}else l="\\u",4096>h&&(l+="0");l+=h.toString(16).toUpperCase()}f=
x7[f]=l}f=e+f}e=f}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Xf(g.sf("b/12014412"),d);a.Qj.open();a.Qj.write(g.Tf(c));a.Qj.close();a.Qj.parentWindow.m=(0,g.E)(a.qW,a);a.Qj.parentWindow.d=(0,g.E)(a.WM,a,!0);a.Qj.parentWindow.rpcClose=(0,g.E)(a.WM,a,!1);c=a.Qj.createElement("DIV");a.Qj.parentWindow.document.body.appendChild(c);d=g.Gf(a.Eo.toString());d=g.ng(g.Cf(d));d=g.Xf(g.sf("b/12014412"),'<iframe src="'+d+'"></iframe>');g.Zf(c,d);a.i.Aj(1)},t7=function(a){a.fH=Date.now()+
a.u;
xTa(a,a.u)},xTa=function(a,b){if(null!=a.Tt)throw Error("WatchDog timer not null");
a.Tt=o7((0,g.E)(a.xW,a),b)},y7=function(a){a.Tt&&(g.C.clearTimeout(a.Tt),a.Tt=null)},w7=function(a){a.i.nf()||a.pp||a.i.Xx(a)},v7=function(a){y7(a);
g.fe(a.LA);a.LA=null;a.I.stop();g.gk(a.C);if(a.Lf){var b=a.Lf;a.Lf=null;b.abort();b.dispose()}a.Qj&&(a.Qj=null)},z7=function(a,b){try{a.i.PM(a,b),a.i.Aj(4)}catch(c){}},zTa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;yTa(a,b,function(h){h?c(!0):g.C.setTimeout(function(){zTa(a,b,c,d,f)},f)})}},yTa=function(a,b,c){var d=new Image;
d.onload=function(){try{A7(d),c(!0)}catch(e){}};
d.onerror=function(){try{A7(d),c(!1)}catch(e){}};
d.onabort=function(){try{A7(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{A7(d),c(!1)}catch(e){}};
g.C.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
HSa(d,a)},A7=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},ATa=function(a){this.i=a;
this.u=new n7},BTa=function(a){var b=B7(a.i,a.Qu,"/mail/images/cleardot.gif");
O6(b);zTa(b.toString(),5E3,(0,g.E)(a.oR,a),3,2E3);a.Aj(1)},D7=function(a){var b=a.i.X;
if(null!=b)q7(5),b?(q7(11),C7(a.i,a,!1)):(q7(12),C7(a.i,a,!0));else if(a.ph=new r7(a,void 0,void 0,void 0),a.ph.Yo=a.lC,b=a.i,b=B7(b,b.nx()?a.Bu:null,a.mC),q7(5),!g.Cc||g.uc(10))P6(b,"TYPE","xmlhttp"),s7(a.ph,b,!1,a.Bu,!1);else{P6(b,"TYPE","html");var c=a.ph;a=!!a.Bu;c.It=3;c.Um=O6(b.clone());wTa(c,a)}},E7=function(a,b,c){this.i=1;
this.u=[];this.C=[];this.D=new n7;this.S=a||null;this.X=null!=b?b:null;this.I=c||!1},CTa=function(a,b){this.i=a;
this.map=b;this.context=null},DTa=function(a,b,c,d){g.ie.call(this,"timingevent",a);
this.size=b;this.bx=d},ETa=function(a){g.ie.call(this,"serverreachability",a)},HTa=function(a){FTa(a);
if(3==a.i){var b=a.qw++,c=a.Ry.clone();g.Yj(c,"SID",a.B);g.Yj(c,"RID",b);g.Yj(c,"TYPE","terminate");F7(a,c);b=new r7(a,a.B,b,void 0);b.It=2;b.Um=O6(c.clone());HSa(new Image,b.Um.toString());b.ut=Date.now();t7(b)}GTa(a)},ITa=function(a){a.OR(1,0);
a.Ry=B7(a,null,a.nC);G7(a)},FTa=function(a){a.Ym&&(a.Ym.abort(),a.Ym=null);
a.Ie&&(a.Ie.cancel(),a.Ie=null);a.Fl&&(g.C.clearTimeout(a.Fl),a.Fl=null);H7(a);a.Vg&&(a.Vg.cancel(),a.Vg=null);a.vn&&(g.C.clearTimeout(a.vn),a.vn=null)},JTa=function(a,b){if(0==a.i)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new CTa(a.rT++,b));2!=a.i&&3!=a.i||G7(a)},KTa=function(a){var b=0;
a.Ie&&b++;a.Vg&&b++;return b},G7=function(a){a.Vg||a.vn||(a.vn=o7((0,g.E)(a.UM,a),0),a.ls=0)},MTa=function(a,b){if(1==a.i){if(!b){a.qw=Math.floor(1E5*Math.random());
b=a.qw++;var c=new r7(a,"",b,void 0);c.Yo=a.Yj;var d=I7(a),e=a.Ry.clone();g.Yj(e,"RID",b);g.Yj(e,"CVER","1");F7(a,e);sTa(c,e,d);a.Vg=c;a.i=2}}else 3==a.i&&(b?LTa(a,b):0==a.u.length||a.Vg||LTa(a))},LTa=function(a,b){if(b)if(6<a.qp){a.u=a.C.concat(a.u);
a.C.length=0;var c=a.qw-1;b=I7(a)}else c=b.S,b=b.xq;else c=a.qw++,b=I7(a);var d=a.Ry.clone();g.Yj(d,"SID",a.B);g.Yj(d,"RID",c);g.Yj(d,"AID",a.Ns);F7(a,d);c=new r7(a,a.B,c,a.ls+1);c.Yo=a.Yj;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Vg=c;sTa(c,d,b)},F7=function(a,b){a.Mf&&(a=a.Mf.jK())&&g.qe(a,function(c,d){g.Yj(b,d,c)})},I7=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.qp&&0<b){var d=a.u[0].i;c.push("ofs="+d)}else d=0;for(var e={},f=0;f<b;e={Xq:e.Xq},f++){e.Xq=a.u[f].i;var h=a.u[f].map;e.Xq=6>=a.qp?f:e.Xq-d;try{g.qe(h,function(l){return function(m,n){c.push("req"+l.Xq+"_"+n+"="+encodeURIComponent(m))}}(e))}catch(l){c.push("req"+e.Xq+"_type="+encodeURIComponent("_badmap"))}}a.C=a.C.concat(a.u.splice(0,b));
return c.join("&")},NTa=function(a){a.Ie||a.Fl||(a.K=1,a.Fl=o7((0,g.E)(a.TM,a),0),a.Mr=0)},J7=function(a){if(a.Ie||a.Fl||3<=a.Mr)return!1;
a.K++;a.Fl=o7((0,g.E)(a.TM,a),OTa(a,a.Mr));a.Mr++;return!0},C7=function(a,b,c){a.tB=c;
a.Zj=b.rl;a.I||ITa(a)},H7=function(a){null!=a.Ap&&(g.C.clearTimeout(a.Ap),a.Ap=null)},OTa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},K7=function(a,b){if(2==b||9==b){var c=null;
a.Mf&&(c=null);var d=(0,g.E)(a.AX,a);c||(c=new g.Qj("//www.google.com/images/cleardot.gif"),O6(c));yTa(c.toString(),1E4,d)}else q7(2);PTa(a,b)},PTa=function(a,b){a.i=0;
a.Mf&&a.Mf.wJ(b);GTa(a);FTa(a)},GTa=function(a){a.i=0;
a.Zj=-1;if(a.Mf)if(0==a.C.length&&0==a.u.length)a.Mf.cD();else{g.Xb(a.C);var b=g.Xb(a.u);a.C.length=0;a.u.length=0;a.Mf.cD(b)}},B7=function(a,b,c){var d=g.Zj(c);
if(""!=d.i)b&&g.Sj(d,b+"."+d.i),g.Tj(d,d.B);else{var e=window.location;d=QSa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.xv&&g.qe(a.xv,function(f,h){g.Yj(d,h,f)});
g.Yj(d,"VER",a.qp);F7(a,d);return d},QTa=function(){},RTa=function(){this.i=[];
this.u=[]},STa=function(a,b){this.action=a;
this.params=b||{}},L7=function(a,b){g.H.call(this);
this.i=new g.L(this.hW,0,this);g.I(this,this.i);this.Sf=5E3;this.u=0;if("function"===typeof a)b&&(a=(0,g.E)(a,b));else if(a&&"function"===typeof a.handleEvent)a=(0,g.E)(a.handleEvent,a);else throw Error("Invalid listener argument");this.B=a},M7=function(a,b,c,d,e){c=void 0===c?!1:c;
d=void 0===d?function(){return""}:d;
e=void 0===e?!1:e;this.va=a;this.I=b;this.B=new g.yr;this.u=new L7(this.eX,this);this.i=null;this.ma=!1;this.D=null;this.X="";this.S=this.C=0;this.K=[];this.Aa=c;this.Z=d;this.Ba=e},TTa=function(a){return{firstTestResults:[""],
secondTestResults:!a.i.tB,sessionId:a.i.B,arrayId:a.i.Ns}},UTa=function(a,b){a.S=b||0;
a.u.stop();N7(a);a.i&&(3==a.i.getState()&&MTa(a.i),HTa(a.i));a.S=0},O7=function(a){return!!a.i&&3==a.i.getState()},N7=function(a){if(a.i){var b=a.Z(),c=a.i.Yj||{};
b?c["x-youtube-lounge-xsrf-token"]=b:delete c["x-youtube-lounge-xsrf-token"];a.i.Yj=c}},P7=function(a){this.port=this.domain="";
this.i="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.ki(4,a))||"";b&&(this.port=":"+b);this.domain=g.li(a)||"";a=g.zb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wb(a,"10.0")&&(this.u=!1))},Q7=function(a,b){var c=a.i;
a.u&&(c="https://"+a.domain+a.port+a.i);return g.wi(c+b,{})},R7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Pa(a.C,d,!0),onError:g.Pa(a.B,e),onTimeout:g.Pa(a.D,e)};c&&(a.postParams=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Kt(b,a)},YTa=function(){var a=VTa;
WTa();S7.push(a);XTa()},T7=function(a,b){WTa();
var c=ZTa(a,String(b));g.Qb(S7)?$Ta(c):(XTa(),g.kc(S7,function(d){d(c)}))},WTa=function(){S7||(S7=g.Ga("yt.mdx.remote.debug.handlers_")||[],g.Fa("yt.mdx.remote.debug.handlers_",S7,void 0))},$Ta=function(a){var b=(U7+1)%50;
U7=b;V7[b]=a;W7||(W7=49==b)},XTa=function(){var a=S7;
if(V7[0]){var b=W7?U7:-1;do{b=(b+1)%50;var c=V7[b];g.kc(a,function(d){d(c)})}while(b!=U7);
V7=Array(50);U7=-1;W7=!1}},ZTa=function(a,b){var c=(Date.now()-aUa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},X7=function(a){g.Zx.call(this);
this.I=a;this.screens=[]},bUa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c)return a=c.name,c.id=b.id||c.id,c.name=b.name,c.token=b.token,c.uuid=b.uuid||c.uuid,c.name!=a;a.screens.push(b);return!0},cUa=function(a,b){var c=a.screens.length!=b.length;
a.screens=g.No(a.screens,function(f){return!!Z6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=bUa(a,b[d])||c;return c},dUa=function(a,b){var c=a.screens.length;
a.screens=g.No(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},Y7=function(a,b,c,d,e){g.Zx.call(this);
this.B=a;this.K=b;this.C=c;this.I=d;this.D=e;this.u=0;this.i=null;this.Mb=NaN},$7=function(a){X7.call(this,"LocalScreenService");
this.u=a;this.i=NaN;Z7(this);this.info("Initializing with "+X6(this.screens))},eUa=function(a){if(a.screens.length){var b=g.um(a.screens,function(d){return d.id}),c=Q7(a.u,"/pairing/get_lounge_token_batch");
R7(a.u,c,{screen_ids:b.join(",")},(0,g.E)(a.mS,a),(0,g.E)(a.lS,a))}},Z7=function(a){if(g.P("deprecate_pair_servlet_enabled"))return cUa(a,[]);
var b=WSa(bTa());b=g.No(b,function(c){return!c.uuid});
return cUa(a,b)},a8=function(a,b){dTa(g.um(a.screens,USa));
b&&cTa()},c8=function(a,b){g.Zx.call(this);
this.I=b;b=(b=g.Ny("yt-remote-online-screen-ids")||"")?b.split(","):[];for(var c={},d=this.I(),e=0,f=d.length;e<f;++e){var h=d[e].id;c[h]=g.Pb(b,h)}this.i=c;this.D=a;this.B=this.C=NaN;this.u=null;b8("Initialized with "+g.bi(this.i))},d8=function(a,b,c){var d=Q7(a.D,"/pairing/get_screen_availability");
R7(a.D,d,{lounge_token:b.token},(0,g.E)(function(e){e=e.screens||[];for(var f=0,h=e.length;f<h;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.E)(function(){c(!1)},a))},e8=function(a,b){a:if(Q6(b)!=Q6(a.i))var c=!1;
else{c=g.ye(b);for(var d=0,e=c.length;d<e;++d)if(!a.i[c[d]]){c=!1;break a}c=!0}c||(b8("Updated online screens: "+g.bi(a.i)),a.i=b,a.ea("screenChange"));fUa(a)},f8=function(a){isNaN(a.B)||g.ht(a.B);
a.B=g.ft((0,g.E)(a.XF,a),0<a.C&&a.C<g.Sa()?2E4:1E4)},b8=function(a){T7("OnlineScreenService",a)},gUa=function(a){var b={};
g.kc(a.I(),function(c){c.token?b[c.token]=c.id:this.le("Requesting availability of screen w/o lounge token.")});
return b},fUa=function(a){a=g.ye(g.re(a.i,function(b){return b}));
g.hc(a);a.length?g.My("yt-remote-online-screen-ids",a.join(","),60):g.Oy("yt-remote-online-screen-ids")},g8=function(a,b){b=void 0===b?!1:b;
X7.call(this,"ScreenService");this.C=a;this.K=b;this.i=this.u=null;this.B=[];this.D={};hUa(this)},jUa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.D[b]);var h=a.Ih(),l=c?$6(h,c):null;c&&(a.K||l)||(l=$6(h,b));if(l){l.uuid=b;var m=h8(a,l);d8(a.i,m,function(n){e(n?m:null)})}else c?iUa(a,c,(0,g.E)(function(n){var p=h8(this,new U6({name:d,
screenId:c,loungeToken:n,dialId:b||""}));d8(this.i,p,function(q){e(q?p:null)})},a),f):e(null)},kUa=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},lUa=function(a,b,c){d8(a.i,b,c)},iUa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={postParams:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,h){f=h&&h.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Kt(Q7(a.C,"/pairing/get_lounge_token_batch"),e)},mUa=function(a){a.screens=a.u.Ih();
var b=a.D,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+X6(a.screens))},hUa=function(a){i8(a);
a.u=new $7(a.C);a.u.subscribe("screenChange",(0,g.E)(a.vS,a));mUa(a);a.K||(a.B=WSa(g.Ny("yt-remote-automatic-screen-cache")||[]));i8(a);a.info("Initializing automatic screens: "+X6(a.B));a.i=new c8(a.C,(0,g.E)(a.Ih,a,!0));a.i.subscribe("screenChange",(0,g.E)(function(){this.ea("onlineScreenChange")},a))},h8=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=$6(a.B,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.B.push(b),a.K||nUa(a));i8(a);a.D[b.uuid]=b.id;g.My("yt-remote-device-id-map",a.D,31536E3);return b},nUa=function(a){a=g.No(a.B,function(b){return"shortLived"!=b.idType});
g.My("yt-remote-automatic-screen-cache",g.um(a,USa))},i8=function(a){a.D=g.Ny("yt-remote-device-id-map")||{}},j8=function(a,b,c){g.Zx.call(this);
this.Ba=c;this.B=a;this.i=b;this.C=null},k8=function(a,b){a.C=b;
a.ea("sessionScreen",a.C)},oUa=function(a,b){a.C&&(a.C.token=b,h8(a.B,a.C));
a.ea("sessionScreen",a.C)},l8=function(a,b){T7(a.Ba,b)},m8=function(a,b,c){j8.call(this,a,b,"CastSession");
var d=this;this.config_=c;this.u=null;this.Z=(0,g.E)(this.CQ,this);this.Aa=(0,g.E)(this.DW,this);this.ma=g.ft(function(){pUa(d,null)},12E4);
this.K=this.D=this.I=this.S=0;this.va=!1;this.X="unknown"},n8=function(a,b){g.ht(a.K);
a.K=0;0==b?qUa(a):a.K=g.ft(function(){qUa(a)},b)},qUa=function(a){rUa(a,"getLoungeToken");
g.ht(a.D);a.D=g.ft(function(){sUa(a,null)},3E4)},rUa=function(a,b){a.info("sendYoutubeMessage_: "+b+" "+g.bi(void 0));
var c={};c.type=b;a.u?a.u.sendMessage("urn:x-cast:com.google.youtube.mdx",c,g.Ha,(0,g.E)(function(){l8(this,"Failed to send message: "+b+".")},a)):l8(a,"Sending yt message without session: "+g.bi(c))},o8=function(a,b){b?(a.info("onConnectedScreenId_: Received screenId: "+b),a.getScreen()&&a.getScreen().id==b||a.xK(b,function(c){k8(a,c)},function(){return a.yg()},5)):a.yg(Error("Waiting for session status timed out."))},uUa=function(a,b,c){a.info("onConnectedScreenData_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);tUa(a,d,function(e){e?(a.va=!0,h8(a.B,d),k8(a,d),a.X="unknown",n8(a,c)):(g.Ls(Error("CastSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online.")),a.yg())},5)},pUa=function(a,b){g.ht(a.ma);
a.ma=0;b?a.config_.enableCastLoungeToken&&b.loungeToken?b.deviceId?a.getScreen()&&a.getScreen().uuid==b.deviceId||(b.loungeTokenRefreshIntervalMs?uUa(a,{name:a.i.friendlyName,screenId:b.screenId,loungeToken:b.loungeToken,dialId:b.deviceId,screenIdType:"shortLived"},b.loungeTokenRefreshIntervalMs):(g.Ls(Error("No loungeTokenRefreshIntervalMs presents in mdxSessionStatusData: "+JSON.stringify(b)+".")),o8(a,b.screenId))):(g.Ls(Error("No device id presents in mdxSessionStatusData: "+JSON.stringify(b)+
".")),o8(a,b.screenId)):o8(a,b.screenId):a.yg(Error("Waiting for session status timed out."))},sUa=function(a,b){g.ht(a.D);
a.D=0;var c=null;if(b)if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";else c="noLoungeTokenResponse";c?(a.info("Did not receive a new lounge token in onLoungeToken_ with data: "+(JSON.stringify(b)+", error: "+c)),a.X=c,n8(a,3E4)):(oUa(a,b.loungeToken),a.va=!1,a.X="unknown",n8(a,b.loungeTokenRefreshIntervalMs))},tUa=function(a,b,c,d){g.ht(a.I);
a.I=0;lUa(a.B,b,function(e){e||0>d?c(e):a.I=g.ft(function(){tUa(a,b,c,d-1)},300)})},vUa=function(a){g.ht(a.S);
a.S=0;g.ht(a.I);a.I=0;g.ht(a.ma);a.ma=0;g.ht(a.D);a.D=0;g.ht(a.K);a.K=0},p8=function(a,b,c,d){j8.call(this,a,b,"DialSession");
this.config_=d;this.u=this.S=null;this.Aa="";this.Na=c;this.Ka=null;this.ma=g.Ha;this.X=NaN;this.Ia=(0,g.E)(this.DQ,this);this.D=g.Ha;this.K=this.I=0;this.Z=!1;this.va="unknown"},q8=function(a){var b;
return!!(a.config_.enableDialLoungeToken&&(null==(b=a.u)?0:b.getDialAppInfo))},wUa=function(a){a.D=a.B.hI(a.Aa,a.i.label,a.i.friendlyName,q8(a),function(b,c){a.D=g.Ha;
a.Z=!0;k8(a,b);"shortLived"==b.idType&&0<c&&r8(a,c)},function(b){a.D=g.Ha;
a.yg(b)})},xUa=function(a){var b={};
b.pairingCode=a.Aa;b.theme=a.Na;gTa()&&(b.env_useStageMdx=1);return g.ui(b)},s8=function(a){return new Promise(function(b){a.Aa=Y6();
if(a.Ka){var c=new chrome.cast.DialLaunchResponse(!0,xUa(a));b(c);wUa(a)}else a.ma=function(){g.ht(a.X);a.ma=function(){};
a.X=NaN;var d=new chrome.cast.DialLaunchResponse(!0,xUa(a));b(d);wUa(a)},a.X=g.ft(function(){a.ma()},100)})},zUa=function(a,b,c){a.info("initOnConnectedScreenDataPromise_: Received screenData: "+JSON.stringify(b));
var d=new U6(b);return(new Promise(function(e){yUa(a,d,function(f){f?(a.Z=!0,h8(a.B,d),k8(a,d),r8(a,c)):g.Ls(Error("DialSession, RemoteScreen from screenData: "+JSON.stringify(b)+" is not online."));e(f)},5)})).then(function(e){return e?new chrome.cast.DialLaunchResponse(!1):s8(a)})},AUa=function(a,b){var c=a.S.receiver.label,d=a.i.friendlyName;
return(new Promise(function(e){jUa(a.B,c,b,d,function(f){f&&f.token&&k8(a,f);e(f)},function(f){l8(a,"Failed to get DIAL screen: "+f);
e(null)})})).then(function(e){return e&&e.token?new chrome.cast.DialLaunchResponse(!1):s8(a)})},yUa=function(a,b,c,d){g.ht(a.I);
a.I=0;lUa(a.B,b,function(e){e||0>d?c(e):a.I=g.ft(function(){yUa(a,b,c,d-1)},300)})},r8=function(a,b){a.info("getDialAppInfoWithTimeout_ "+b);
q8(a)&&(g.ht(a.K),a.K=0,0==b?BUa(a):a.K=g.ft(function(){BUa(a)},b))},BUa=function(a){q8(a)&&a.u.getDialAppInfo(function(b){a.info("getDialAppInfo dialLaunchData: "+JSON.stringify(b));
b=b.extraData||{};var c=null;if(b.loungeToken){var d;(null==(d=a.getScreen())?void 0:d.token)==b.loungeToken&&(c="staleLoungeToken")}else c="missingLoungeToken";c?(a.va=c,r8(a,3E4)):(a.Z=!1,a.va="unknown",oUa(a,b.loungeToken),r8(a,b.loungeTokenRefreshIntervalMs))},function(b){a.info("getDialAppInfo error: "+b);
a.va="noLoungeTokenResponse";r8(a,3E4)})},CUa=function(a){g.ht(a.I);
a.I=0;g.ht(a.K);a.K=0;a.D();a.D=function(){};
g.ht(a.X)},t8=function(a,b){j8.call(this,a,b,"ManualSession");
this.u=g.ft((0,g.E)(this.Os,this,null),150)},u8=function(a,b){g.Zx.call(this);
this.config_=b;this.u=a;this.S=b.appId||"233637DE";this.C=b.theme||"cl";this.X=b.disableCastApi||!1;this.I=b.forceMirroring||!1;this.i=null;this.K=!1;this.B=[];this.D=(0,g.E)(this.uV,this)},DUa=function(a,b){return b?g.Mb(a.B,function(c){return V6(b,c.label)},a):null},v8=function(a){T7("Controller",a)},VTa=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},w8=function(a){return a.K||!!a.B.length||!!a.i},x8=function(a,b,c){b!=a.i&&(g.fe(a.i),(a.i=b)?(c?a.ea("yt-remote-cast2-receiver-resumed",
b.i):a.ea("yt-remote-cast2-receiver-selected",b.i),b.subscribe("sessionScreen",(0,g.E)(a.SM,a,b)),b.subscribe("sessionFailed",function(){return EUa(a,b)}),b.getScreen()?a.ea("yt-remote-cast2-session-change",b.getScreen()):c&&a.i.Os(null)):a.ea("yt-remote-cast2-session-change",null))},EUa=function(a,b){a.i==b&&a.ea("yt-remote-cast2-session-failed")},FUa=function(a){var b=a.u.gI(),c=a.i&&a.i.i;
a=g.um(b,function(d){c&&V6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=DUa(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},KUa=function(a,b,c,d){d.disableCastApi?y8("Cannot initialize because disabled by Mdx config."):GUa()?HUa(b,d)&&(z8(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?IUa(a,c):(window.__onGCastApiAvailable=function(e,f){e?IUa(a,c):(A8("Failed to load cast API: "+f),B8(!1),z8(!1),g.Oy("yt-remote-cast-available"),g.Oy("yt-remote-cast-receiver"),
JUa(),c(!1))},d.loadCastApiSetupScript?g.Qy("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?60<=g7()&&nTa():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?i7():89<=g7()?pTa():(j7(),h7(oTa.map(kTa))))):y8("Cannot initialize because not running Chrome")},JUa=function(){y8("dispose");
var a=C8();a&&a.dispose();g.Fa("yt.mdx.remote.cloudview.instance_",null,void 0);LUa(!1);g.pv(D8);D8.length=0},E8=function(){return!!g.Ny("yt-remote-cast-installed")},MUa=function(){var a=g.Ny("yt-remote-cast-receiver");
return a?a.friendlyName:null},NUa=function(){y8("clearCurrentReceiver");
g.Oy("yt-remote-cast-receiver")},OUa=function(){return E8()?C8()?C8().getCastSession():(A8("getCastSelector: Cast is not initialized."),null):(A8("getCastSelector: Cast API is not installed!"),null)},G8=function(){E8()?C8()?F8()?(y8("Requesting cast selector."),C8().requestSession()):(y8("Wait for cast API to be ready to request the session."),D8.push(g.ov("yt-remote-cast2-api-ready",G8))):A8("requestCastSelector: Cast is not initialized."):A8("requestCastSelector: Cast API is not installed!")},H8=
function(a,b){F8()?C8().setConnectedScreenStatus(a,b):A8("setConnectedScreenStatus called before ready.")},GUa=function(){var a=0<=g.zb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Zi||a},PUa=function(a,b){C8().init(a,b)},HUa=function(a,b){var c=!1;
C8()||(a=new u8(a,b),a.subscribe("yt-remote-cast2-availability-change",function(d){g.My("yt-remote-cast-available",d);S6("yt-remote-cast2-availability-change",d)}),a.subscribe("yt-remote-cast2-receiver-selected",function(d){y8("onReceiverSelected: "+d.friendlyName);
g.My("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-selected",d)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(d){y8("onReceiverResumed: "+d.friendlyName);
g.My("yt-remote-cast-receiver",d);S6("yt-remote-cast2-receiver-resumed",d)}),a.subscribe("yt-remote-cast2-session-change",function(d){y8("onSessionChange: "+W6(d));
d||g.Oy("yt-remote-cast-receiver");S6("yt-remote-cast2-session-change",d)}),g.Fa("yt.mdx.remote.cloudview.instance_",a,void 0),c=!0);
y8("cloudview.createSingleton_: "+c);return c},C8=function(){return g.Ga("yt.mdx.remote.cloudview.instance_")},IUa=function(a,b){B8(!0);
z8(!1);PUa(a,function(c){c?(LUa(!0),g.qv("yt-remote-cast2-api-ready")):(A8("Failed to initialize cast API."),B8(!1),g.Oy("yt-remote-cast-available"),g.Oy("yt-remote-cast-receiver"),JUa());b(c)})},y8=function(a){T7("cloudview",a)},A8=function(a){T7("cloudview",a)},B8=function(a){y8("setCastInstalled_ "+a);
g.My("yt-remote-cast-installed",a)},F8=function(){return!!g.Ga("yt.mdx.remote.cloudview.apiReady_")},LUa=function(a){y8("setApiReady_ "+a);
g.Fa("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z8=function(a){g.Fa("yt.mdx.remote.cloudview.initializing_",a,void 0)},I8=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.I=this.K=0;this.trackData=null;this.hasNext=this.Hk=!1;this.S=this.D=this.i=this.C=0;this.B=NaN;this.u=!1;this.reset(a)},J8=function(a){a.audioTrackId=null;
a.trackData=null;a.playerState=-1;a.Hk=!1;a.hasNext=!1;a.K=0;a.I=g.Sa();a.C=0;a.i=0;a.D=0;a.S=0;a.B=NaN;a.u=!1},K8=function(a){return a.Ec()?(g.Sa()-a.I)/1E3:0},L8=function(a,b){a.K=b;
a.I=g.Sa()},M8=function(a){switch(a.playerState){case 1:case 1081:return(g.Sa()-a.I)/1E3+a.K;
case -1E3:return 0}return a.K},N8=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J8(a)},O8=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Ke(a.trackData);b.hasPrevious=a.Hk;b.hasNext=a.hasNext;b.playerTime=a.K;b.playerTimeAt=a.I;b.seekableStart=a.C;b.seekableEnd=a.i;b.duration=a.D;b.loadedTime=a.S;b.liveIngestionTime=a.B;return b},Q8=function(a,b){g.Zx.call(this);
this.B=0;this.C=a;this.I=[];this.D=new RTa;this.u=this.i=null;this.X=(0,g.E)(this.cU,this);this.K=(0,g.E)(this.Bw,this);this.S=(0,g.E)(this.bU,this);this.ma=(0,g.E)(this.jU,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.nG,this),QUa(this))):c=3;0!=c&&(b?this.nG(c):g.ft((0,g.E)(function(){this.nG(c)},this),0));
(a=OUa())&&P8(this,a);this.subscribe("yt-remote-cast2-session-change",this.ma)},R8=function(a){return new I8(a.C.getPlayerContextData())},QUa=function(a){g.kc("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange multiStateLoopEnabled loopModeChange".split(" "),function(b){this.I.push(this.C.subscribe(b,g.Pa(this.sV,b),this))},a)},RUa=function(a){g.kc(a.I,function(b){this.C.unsubscribeByKey(b)},a);
a.I.length=0},S8=function(a){return 1==a.getState()},T8=function(a,b){var c=a.D;
50>c.i.length+c.u.length&&a.D.u.push(b)},V8=function(a,b,c){var d=R8(a);
L8(d,c);-1E3!=d.playerState&&(d.playerState=b);U8(a,d)},W8=function(a,b,c){a.C.sendMessage(b,c)},U8=function(a,b){RUa(a);
a.C.setPlayerContextData(O8(b));QUa(a)},P8=function(a,b){a.u&&(a.u.removeUpdateListener(a.X),a.u.removeMediaListener(a.K),a.Bw(null));
a.u=b;a.u&&(T7("CP","Setting cast session: "+a.u.sessionId),a.u.addUpdateListener(a.X),a.u.addMediaListener(a.K),a.u.media.length&&a.Bw(a.u.media[0]))},SUa=function(a){var b=a.i.media,c=a.i.customData;
if(b&&c){var d=R8(a);b.contentId!=d.videoId&&T7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;L8(d,a.i.getEstimatedTime());U8(a,d)}else T7("CP","No cast media video. Ignoring state update.")},X8=function(a,b,c){return(0,g.E)(function(d){this.le("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.le("Retrying "+b+" using MDx browser channel."),W8(this,b,c))},a)},Y8=function(a,b,c,d){d=void 0===d?!1:d;
g.Zx.call(this);this.D=NaN;this.va=!1;this.S=this.K=this.ma=this.Z=NaN;this.X=[];this.C=this.I=this.B=this.jc=this.i=null;this.Ia=a;this.Ba=d;this.X.push(g.Iu(window,"beforeunload",(0,g.E)(this.hS,this)));this.u=[];this.jc=new I8;this.Ka=b.id;this.Aa=b.idType;this.i=TUa(this,c);this.i.subscribe("handlerOpened",this.gU,this);this.i.subscribe("handlerClosed",this.dU,this);this.i.subscribe("handlerError",this.eU,this);this.i.subscribe("handlerMessage",this.fU,this);this.i.XA(b.token);this.subscribe("remoteQueueChange",
function(){var e=this.jc.videoId;g.Py()&&g.My("yt-remote-session-video-id",e)},this)},UUa=function(a){return g.Mb(a.u,function(b){return"LOUNGE_SCREEN"==b.type})},Z8=function(a){T7("conn",a)},TUa=function(a,b){return new M7(Q7(a.Ia,"/bc"),b,!1,function(){return a.lI()},"shortLived"==a.Aa)},$8=function(a,b){a.ea("proxyStateChange",b)},VUa=function(a){a.D=g.ft((0,g.E)(function(){Z8("Connecting timeout");
this.Zr(1)},a),2E4)},a9=function(a){g.ht(a.D);
a.D=NaN},b9=function(a){g.ht(a.Z);
a.Z=NaN},WUa=function(a){c9(a);
a.ma=g.ft((0,g.E)(function(){d9(this,"getNowPlaying")},a),2E4)},c9=function(a){g.ht(a.ma);
a.ma=NaN},YUa=function(a,b){var c=null;
if(b){var d=UUa(a);d&&(c={clientName:d.clientName,deviceMake:d.brand,deviceModel:d.model,osVersion:d.osVersion})}g.Fa("yt.mdx.remote.remoteClient_",c,void 0);b&&(a9(a),b9(a));c=O7(a.i)&&isNaN(a.D);b==c?b&&($8(a,1),d9(a,"getSubtitlesTrack")):b?(a.wK()&&a.jc.reset(),$8(a,1),d9(a,"getNowPlaying"),XUa(a)):a.Zr(1)},ZUa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.jc.videoId&&(g.Fe(b.params)?a.jc.trackData=null:a.jc.trackData=b.params,a.ea("remotePlayerChange"))},$Ua=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.jc.listId=b.params.listId||a.jc.listId;N8(a.jc,c,d);a.ea("remoteQueueChange")},bVa=function(a,b){b.params=b.params||{};
$Ua(a,b);aVa(a,b);a.ea("autoplayDismissed")},aVa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
L8(a.jc,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.jc.playerState&&(c=-1E3);a.jc.playerState=c;c=Number(b.params.loadedTime);a.jc.S=isNaN(c)?0:c;a.jc.Lj(Number(b.params.duration));c=a.jc;var d=Number(b.params.liveIngestionTime);c.B=d;c.u=isNaN(d)?!1:!0;c=a.jc;d=Number(b.params.seekableStartTime);b=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.i=isNaN(b)?0:b;1==a.jc.playerState?WUa(a):c9(a);a.ea("remotePlayerChange")},cVa=function(a,b){if(-1E3!=a.jc.playerState){var c=
1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.jc.playerState=c;b=parseInt(b.params.currentTime,10);L8(a.jc,isNaN(b)?0:b);a.ea("remotePlayerChange")}},dVa=function(a,b){var c="true"==b.params.muted;
a.jc.volume=parseInt(b.params.volume,10);a.jc.muted=c;a.ea("remotePlayerChange")},eVa=function(a,b){a.I=b.params.videoId;
a.ea("nowAutoplaying",parseInt(b.params.timeout,10))},fVa=function(a,b){var c="true"==b.params.hasNext;
a.jc.Hk="true"==b.params.hasPrevious;a.jc.hasNext=c;a.ea("previousNextChange")},XUa=function(a){g.ht(a.S);
a.S=g.ft((0,g.E)(a.Zr,a,1),864E5)},d9=function(a,b,c){c?Z8("Sending: action="+b+", params="+g.bi(c)):Z8("Sending: action="+b);
a.i.sendMessage(b,c)},e9=function(a){X7.call(this,"ScreenServiceProxy");
this.Re=a;this.i=[];this.i.push(this.Re.$_s("screenChange",(0,g.E)(this.HQ,this)));this.i.push(this.Re.$_s("onlineScreenChange",(0,g.E)(this.YU,this)))},jVa=function(a,b){fTa();
if(!f7||!f7.get("yt-remote-disable-remote-module-for-dev")){b=g.O("MDX_CONFIG")||b;YSa();d7();f9||(f9=new P7(b?b.loungeApiHost:void 0),gTa()&&(f9.i="/api/loungedev"));g9||(g9=g.Ga("yt.mdx.remote.deferredProxies_")||[],g.Fa("yt.mdx.remote.deferredProxies_",g9,void 0));gVa();var c=h9();if(!c){var d=new g8(f9,b?b.disableAutomaticScreenCache||!1:!1);g.Fa("yt.mdx.remote.screenService_",d,void 0);c=h9();var e={};b&&(e={appId:b.appId,disableDial:b.disableDial,theme:b.theme,loadCastApiSetupScript:b.loadCastApiSetupScript,
disableCastApi:b.disableCastApi,enableDialLoungeToken:b.enableDialLoungeToken,enableCastLoungeToken:b.enableCastLoungeToken,forceMirroring:b.forceMirroring});g.Fa("yt.mdx.remote.enableConnectWithInitialState_",b?b.enableConnectWithInitialState||!1:!1,void 0);KUa(a,d,function(f){f?i9()&&H8(i9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){S6("yt-remote-receiver-availability-change")})},e)}b&&!g.Ga("yt.mdx.remote.initialized_")&&(g.Fa("yt.mdx.remote.initialized_",!0,void 0),j9("Initializing: "+
g.bi(b)),k9.push(g.ov("yt-remote-cast2-api-ready",function(){S6("yt-remote-api-ready")})),k9.push(g.ov("yt-remote-cast2-availability-change",function(){S6("yt-remote-receiver-availability-change")})),k9.push(g.ov("yt-remote-cast2-receiver-selected",function(){l9(null);
S6("yt-remote-auto-connect","cast-selector-receiver")})),k9.push(g.ov("yt-remote-cast2-receiver-resumed",function(){S6("yt-remote-receiver-resumed","cast-selector-receiver")})),k9.push(g.ov("yt-remote-cast2-session-change",hVa)),k9.push(g.ov("yt-remote-connection-change",function(f){f?H8(i9(),"YouTube TV"):m9()||(H8(null,null),NUa())})),k9.push(g.ov("yt-remote-cast2-session-failed",function(){S6("yt-remote-connection-failed")})),a=n9(),b.isAuto&&(a.id+="#dial"),e=b.capabilities||[],g.P("desktop_enable_autoplay")&&
e.push("atp"),0<e.length&&(a.capabilities=e),a.name=b.device,a.app=b.app,(b=b.theme)&&(a.theme=b),j9(" -- with channel params: "+g.bi(a)),a?(g.My("yt-remote-session-app",a.app),g.My("yt-remote-session-name",a.name)):(g.Oy("yt-remote-session-app"),g.Oy("yt-remote-session-name")),g.Fa("yt.mdx.remote.channelParams_",a,void 0),c.start(),i9()||iVa())}},kVa=function(){var a=h9().Re.$_gos();
var b=o9();b&&p9()&&(Z6(a,b)||a.push(b));return XSa(a)},q9=function(){var a=lVa();
!a&&E8()&&MUa()&&(a={key:"cast-selector-receiver",name:MUa()});return a},lVa=function(){var a=kVa(),b=o9();
b||(b=m9());return g.Mb(a,function(c){return b&&V6(b,c.key)?!0:!1})},o9=function(){var a=i9();
if(!a)return null;var b=h9().Ih();return $6(b,a)},hVa=function(a){j9("remote.onCastSessionChange_: "+W6(a));
if(a){var b=o9();if(b&&b.id==a.id){if(H8(b.id,"YouTube TV"),"shortLived"==a.idType&&(a=a.token))r9&&(r9.token=a),(b=p9())&&b.XA(a)}else b&&s9(),t9(a,1)}else p9()&&s9()},s9=function(){F8()?C8().stopSession():A8("stopSession called before API ready.");
var a=p9();a&&(a.disconnect(1),u9(null))},v9=function(){var a=p9();
return!!a&&3!=a.getProxyState()},j9=function(a){T7("remote",a)},h9=function(){if(!w9){var a=g.Ga("yt.mdx.remote.screenService_");
w9=a?new e9(a):null}return w9},i9=function(){return g.Ga("yt.mdx.remote.currentScreenId_")},mVa=function(a){g.Fa("yt.mdx.remote.currentScreenId_",a,void 0)},nVa=function(){return g.Ga("yt.mdx.remote.connectData_")},l9=function(a){g.Fa("yt.mdx.remote.connectData_",a,void 0)},p9=function(){return g.Ga("yt.mdx.remote.connection_")},u9=function(a){var b=p9();
l9(null);a||mVa("");g.Fa("yt.mdx.remote.connection_",a,void 0);g9&&(g.kc(g9,function(c){c(a)}),g9.length=0);
b&&!a?S6("yt-remote-connection-change",!1):!b&&a&&S6("yt-remote-connection-change",!0)},m9=function(){var a=g.Py();
if(!a)return null;var b=h9();if(!b)return null;b=b.Ih();return $6(b,a)},t9=function(a,b){i9();
o9()&&o9();if(x9)r9=a;else{mVa(a.id);var c=g.Ga("yt.mdx.remote.enableConnectWithInitialState_")||!1;a=new Y8(f9,a,n9(),c);a.connect(b,nVa());a.subscribe("beforeDisconnect",function(d){S6("yt-remote-before-disconnect",d)});
a.subscribe("beforeDispose",function(){p9()&&(p9(),u9(null))});
a.subscribe("browserChannelAuthError",function(){var d=o9();d&&"shortLived"==d.idType&&(F8()?C8().handleBrowserChannelAuthError():A8("refreshLoungeToken called before API ready."))});
u9(a)}},iVa=function(){var a=m9();
a?(j9("Resume connection to: "+W6(a)),t9(a,0)):(e7(),NUa(),j9("Skipping connecting because no session screen found."))},gVa=function(){var a=n9();
if(g.Fe(a)){a=c7();var b=g.Ny("yt-remote-session-name")||"",c=g.Ny("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Fa("yt.mdx.remote.channelParams_",a,void 0)}},n9=function(){return g.Ga("yt.mdx.remote.channelParams_")||{}},y9=function(a,b,c){g.H.call(this);
var d=this;this.u=a;this.J=b;this.Ub=c;this.events=new g.hD(this);this.ma=this.events.T(this.J,"onVolumeChange",function(e){oVa(d,e)});
this.D=!1;this.I=new g.MJ(64);this.i=new g.L(this.ZN,500,this);this.B=new g.L(this.aO,1E3,this);this.S=new k7(this.RX,0,this);this.C={};this.X=new g.L(this.IO,1E3,this);this.K=new l7(this.seekTo,1E3,this);this.Z=g.Ha;g.I(this,this.events);this.events.T(b,"onCaptionsTrackListChanged",this.JU);this.events.T(b,"captionschanged",this.ZT);this.events.T(b,"captionssettingschanged",this.gO);this.events.T(b,"videoplayerreset",this.qA);this.events.T(b,"mdxautoplaycancel",function(){d.Ub.SJ()});
a=this.Ub;a.isDisposed();a.subscribe("proxyStateChange",this.OM,this);a.subscribe("remotePlayerChange",this.Fw,this);a.subscribe("remoteQueueChange",this.qA,this);a.subscribe("previousNextChange",this.KM,this);a.subscribe("nowAutoplaying",this.EM,this);a.subscribe("autoplayDismissed",this.hM,this);g.I(this,this.i);g.I(this,this.B);g.I(this,this.S);g.I(this,this.X);g.I(this,this.K);this.gO();this.qA();this.Fw()},oVa=function(a,b){if(z9(a)){a.Ub.unsubscribe("remotePlayerChange",a.Fw,a);
var c=Math.round(b.volume);b=!!b.muted;var d=R8(a.Ub);if(c!==d.volume||b!==d.muted)a.Ub.setVolume(c,b),a.X.start();a.Ub.subscribe("remotePlayerChange",a.Fw,a)}},pVa=function(a){a.Yb(0);
a.i.stop();a.Vb(new g.MJ(64))},A9=function(a,b){if(z9(a)&&!a.D){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Me(c,b));a.Ub.kI(a.J.getVideoData(1).videoId,c);a.C=R8(a.Ub).trackData}},B9=function(a,b){var c=a.J.getPlaylist();
if(null===c||void 0===c?0:c.listId){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Ub.playVideo(c.videoId,b,d,e,c.playerParams,c.Za,NSa(c));a.Vb(new g.MJ(1))},qVa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{UK:1});
c&&c.length?(a.J.setOption("captions","track",b),a.D=!1):(a.J.loadModule("captions"),a.D=!0)}else a.J.setOption("captions","track",{})},z9=function(a){return R8(a.Ub).videoId===a.J.getVideoData(1).videoId},C9=function(){g.W.call(this,{G:"div",
L:"ytp-mdx-popup-dialog",W:{role:"dialog"},U:[{G:"div",L:"ytp-mdx-popup-dialog-inner-content",U:[{G:"div",L:"ytp-mdx-popup-title",ya:"No has iniciado sesi\u00f3n"},{G:"div",L:"ytp-mdx-popup-description",ya:"Los v\u00eddeos que veas podr\u00edan aparecer en el historial de reproducciones de la TV e influir en las recomendaciones. Puedes evitarlo si cancelas e inicias sesi\u00f3n en YouTube desde tu ordenador."},{G:"div",L:"ytp-mdx-privacy-popup-buttons",U:[{G:"button",Ga:["ytp-button","ytp-mdx-privacy-popup-cancel"],
ya:"Cancelar"},{G:"button",Ga:["ytp-button","ytp-mdx-privacy-popup-confirm"],ya:"Confirmar"}]}]}]});this.i=new g.rL(this,250);this.cancelButton=this.Fa("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.Fa("ytp-mdx-privacy-popup-confirm");g.I(this,this.i);this.T(this.cancelButton,"click",this.u);this.T(this.confirmButton,"click",this.B)},D9=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",U:[{G:"div",L:"ytp-remote-display-status",U:[{G:"div",L:"ytp-remote-display-status-icon",U:[g.xta()]},{G:"div",L:"ytp-remote-display-status-text",ya:"{{statustext}}"}]}]});this.api=a;this.i=new g.rL(this,250);g.I(this,this.i);this.T(a,"presentingplayerstatechange",this.onStateChange);rVa(this,a.Ab())},rVa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
b=g.U(b,128)?g.kI("No se ha podido reproducir el v\u00eddeo en $RECEIVER_NAME",c):b.Ec()||g.U(b,4)?g.kI("El v\u00eddeo se est\u00e1 reproduciendo en $RECEIVER_NAME",c):g.kI("Conectado a $RECEIVER_NAME",c);a.Sa("statustext",b);a.i.show()}else a.i.hide()},E9=function(a,b){g.LP.call(this,"Reproducir en",0,a,b);
this.J=a;this.Bo={};this.T(a,"onMdxReceiversChange",this.D);this.T(a,"presentingplayerstatechange",this.D);this.D()},F9=function(a){g.VM.call(this,a);
this.Ok={key:Y6(),name:"Este ordenador"};this.di=null;this.subscriptions=[];this.KF=this.Ub=null;this.Bo=[this.Ok];this.cn=this.Ok;this.yd=new g.MJ(64);this.xL=0;this.tf=-1;this.Ow=!1;this.Mw=this.jt=null;if(!g.SE(this.player.V())&&!g.TE(this.player.V())){a=this.player;var b=g.yM(a);b&&(b=b.En())&&(b=new E9(a,b),g.I(this,b));b=new D9(a);g.I(this,b);g.IM(a,b.element,4);this.jt=new C9;g.I(this,this.jt);g.IM(a,this.jt.element,4);this.Ow=!!m9()}},G9=function(a){a.Mw&&(a.player.removeEventListener("presentingplayerstatechange",
a.Mw),a.Mw=null)},sVa=function(a,b,c){a.yd=c;
a.player.ea("presentingplayerstatechange",new g.UH(c,b))},H9=function(a,b){if(b.key!==a.cn.key)if(b.key===a.Ok.key)s9();
else{var c;(c=!a.player.V().N("mdx_enable_privacy_disclosure_ui"))||(c=((c=g.O("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.O("SESSION_INDEX")&&!g.O("LOGGED_IN")))||a.Ow||!a.jt);(c?0:g.iF(a.player.V())||g.lF(a.player.V()))&&tVa(a);a.cn=b;if(!a.player.V().N("disable_mdx_connection_in_mdx_module_for_music_web")||!g.TE(a.player.V())){var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&a.player.V().N("should_clear_video_data_on_player_cued_unstarted"))a=
null;else{var f=a.player.getPlaylist();if(f){var h=[];for(var l=0;l<f.length;l++)h[l]=g.PM(f,l).videoId}else h=[e];f=a.player.getCurrentTime(1);a={videoIds:h,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.Za,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=NSa(c))&&(a.locationInfo=c)}j9("Connecting to: "+g.bi(b));"cast-selector-receiver"==b.key?(l9(a||null),b=a||null,F8()?C8().setLaunchParams(b):A8("setLaunchParams called before ready.")):!a&&v9()&&
i9()==b.key?S6("yt-remote-connection-change",!0):(s9(),l9(a||null),a=h9().Ih(),(b=$6(a,b.key))&&t9(b,1))}}},tVa=function(a){a.player.Ab().Ec()?a.player.pauseVideo():(a.Mw=function(b){!a.Ow&&g.WH(b,8)&&(a.player.pauseVideo(),G9(a))},a.player.addEventListener("presentingplayerstatechange",a.Mw));
a.jt&&a.jt.xd();p9()||(x9=!0)},vTa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},x7={"'":"\\'"},TSa={XY:"atp",V9:"ska",H8:"que",C6:"mus",U9:"sus",P2:"dsp",e9:"seq",f6:"mic",H1:"dpa",mZ:"cds",A6:"mlm",F1:"dsdtr"},f7,b7="",mTa=hTa("loadCastFramework")||hTa("loadCastApplicationFramework"),oTa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(k7,g.H);g.k=k7.prototype;g.k.vQ=function(a){this.C=arguments;this.i=!1;this.Mb?this.B=g.Sa()+this.Sf:this.Mb=g.Ah(this.D,this.Sf)};
g.k.stop=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null);this.B=null;this.i=!1;this.C=[]};
g.k.pause=function(){++this.u};
g.k.resume=function(){this.u&&(--this.u,!this.u&&this.i&&(this.i=!1,this.I.apply(null,this.C)))};
g.k.xa=function(){this.stop();k7.ke.xa.call(this)};
g.k.wQ=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null);this.B?(this.Mb=g.Ah(this.D,this.B-g.Sa()),this.B=null):this.u?this.i=!0:(this.i=!1,this.I.apply(null,this.C))};g.w(l7,g.H);g.k=l7.prototype;g.k.fI=function(a){this.B=arguments;this.Mb||this.u?this.i=!0:m7(this)};
g.k.stop=function(){this.Mb&&(g.C.clearTimeout(this.Mb),this.Mb=null,this.i=!1,this.B=null)};
g.k.pause=function(){this.u++};
g.k.resume=function(){this.u--;this.u||!this.i||this.Mb||(this.i=!1,m7(this))};
g.k.xa=function(){g.H.prototype.xa.call(this);this.stop()};n7.prototype.stringify=function(a){return g.C.JSON.stringify(a,void 0)};
n7.prototype.parse=function(a){return g.C.JSON.parse(a,void 0)};var p7=new g.df;g.w(qTa,g.ie);g.k=r7.prototype;g.k.Yo=null;g.k.Fm=!1;g.k.Tt=null;g.k.fH=null;g.k.ut=null;g.k.It=null;g.k.Um=null;g.k.Eo=null;g.k.xq=null;g.k.Lf=null;g.k.xB=0;g.k.Qj=null;g.k.vB=null;g.k.Om=null;g.k.Au=-1;g.k.NN=!0;g.k.pp=!1;g.k.kC=0;g.k.LA=null;var tTa={},u7={};g.k=r7.prototype;g.k.setTimeout=function(a){this.u=a};
g.k.xQ=function(a){a=a.target;var b=this.LA;b&&3==g.Ji(a)?b.fI():this.RO(a)};
g.k.RO=function(a){try{if(a==this.Lf)a:{var b=g.Ji(this.Lf),c=this.Lf.u,d=this.Lf.getStatus();if(g.Cc&&!g.uc(10)||g.Hg&&!g.tc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Oi(this.Lf))break a;this.pp||4!=b||7==c||(8==c||0>=d?this.i.Aj(3):this.i.Aj(2));y7(this);var e=this.Lf.getStatus();this.Au=e;var f=g.Oi(this.Lf);if(this.Fm=200==e){4==b&&v7(this);if(this.D){for(a=!0;!this.pp&&this.xB<f.length;){var h=uTa(this,f);if(h==u7){4==b&&(this.Om=4,q7(15),a=!1);break}else if(h==tTa){this.Om=4;q7(16);a=!1;
break}else z7(this,h)}4==b&&0==f.length&&(this.Om=1,q7(17),a=!1);this.Fm=this.Fm&&a;a||(v7(this),w7(this))}else z7(this,f);this.Fm&&!this.pp&&(4==b?this.i.Xx(this):(this.Fm=!1,t7(this)))}else 400==e&&0<f.indexOf("Unknown SID")?(this.Om=3,q7(13)):(this.Om=0,q7(14)),v7(this),w7(this)}}catch(l){this.Lf&&g.Oi(this.Lf)}finally{}};
g.k.qW=function(a){o7((0,g.E)(this.pW,this,a),0)};
g.k.pW=function(a){this.pp||(y7(this),z7(this,a),t7(this))};
g.k.WM=function(a){o7((0,g.E)(this.oW,this,a),0)};
g.k.oW=function(a){this.pp||(v7(this),this.Fm=a,this.i.Xx(this),this.i.Aj(4))};
g.k.cancel=function(){this.pp=!0;v7(this)};
g.k.xW=function(){this.Tt=null;var a=Date.now();0<=a-this.fH?(2!=this.It&&this.i.Aj(3),v7(this),this.Om=2,q7(18),w7(this)):xTa(this,this.fH-a)};
g.k.getLastError=function(){return this.Om};g.k=ATa.prototype;g.k.lC=null;g.k.ph=null;g.k.MA=!1;g.k.bO=null;g.k.Qy=null;g.k.HE=null;g.k.mC=null;g.k.Yh=null;g.k.rl=-1;g.k.Bu=null;g.k.Qu=null;g.k.connect=function(a){this.mC=a;a=B7(this.i,null,this.mC);q7(3);this.bO=Date.now();var b=this.i.S;null!=b?(this.Bu=b[0],(this.Qu=b[1])?(this.Yh=1,BTa(this)):(this.Yh=2,D7(this))):(P6(a,"MODE","init"),this.ph=new r7(this,void 0,void 0,void 0),this.ph.Yo=this.lC,s7(this.ph,a,!1,null,!0),this.Yh=0)};
g.k.oR=function(a){if(a)this.Yh=2,D7(this);else{q7(4);var b=this.i;b.Zj=b.Ym.rl;K7(b,9)}a&&this.Aj(2)};
g.k.pD=function(a){return this.i.pD(a)};
g.k.abort=function(){this.ph&&(this.ph.cancel(),this.ph=null);this.rl=-1};
g.k.nf=function(){return!1};
g.k.PM=function(a,b){this.rl=a.Au;if(0==this.Yh)if(b){try{var c=this.u.parse(b)}catch(d){a=this.i;a.Zj=this.rl;K7(a,2);return}this.Bu=c[0];this.Qu=c[1]}else a=this.i,a.Zj=this.rl,K7(a,2);else if(2==this.Yh)if(this.MA)q7(7),this.HE=Date.now();else if("11111"==b){if(q7(6),this.MA=!0,this.Qy=Date.now(),a=this.Qy-this.bO,!g.Cc||g.uc(10)||500>a)this.rl=200,this.ph.cancel(),q7(12),C7(this.i,this,!0)}else q7(8),this.Qy=this.HE=Date.now(),this.MA=!1};
g.k.Xx=function(){this.rl=this.ph.Au;if(this.ph.Fm)0==this.Yh?this.Qu?(this.Yh=1,BTa(this)):(this.Yh=2,D7(this)):2==this.Yh&&((!g.Cc||g.uc(10)?!this.MA:200>this.HE-this.Qy)?(q7(11),C7(this.i,this,!1)):(q7(12),C7(this.i,this,!0)));else{0==this.Yh?q7(9):2==this.Yh&&q7(10);var a=this.i;this.ph.getLastError();a.Zj=this.rl;K7(a,2)}};
g.k.nx=function(){return this.i.nx()};
g.k.isActive=function(){return this.i.isActive()};
g.k.Aj=function(a){this.i.Aj(a)};g.k=E7.prototype;g.k.Yj=null;g.k.xv=null;g.k.Vg=null;g.k.Ie=null;g.k.nC=null;g.k.Ry=null;g.k.gJ=null;g.k.Yx=null;g.k.qw=0;g.k.rT=0;g.k.Mf=null;g.k.vn=null;g.k.Fl=null;g.k.Ap=null;g.k.Ym=null;g.k.tB=null;g.k.Ns=-1;g.k.wL=-1;g.k.Zj=-1;g.k.ls=0;g.k.Mr=0;g.k.qp=8;g.Ta(DTa,g.ie);g.Ta(ETa,g.ie);g.k=E7.prototype;g.k.connect=function(a,b,c,d,e){q7(0);this.nC=b;this.xv=c||{};d&&void 0!==e&&(this.xv.OSID=d,this.xv.OAID=e);this.I?(o7((0,g.E)(this.CJ,this,a),100),ITa(this)):this.CJ(a)};
g.k.CJ=function(a){this.Ym=new ATa(this);this.Ym.lC=this.Yj;this.Ym.u=this.D;this.Ym.connect(a)};
g.k.nf=function(){return 0==this.i};
g.k.getState=function(){return this.i};
g.k.UM=function(a){this.vn=null;MTa(this,a)};
g.k.TM=function(){this.Fl=null;this.Ie=new r7(this,this.B,"rpc",this.K);this.Ie.Yo=this.Yj;this.Ie.kC=0;var a=this.gJ.clone();g.Yj(a,"RID","rpc");g.Yj(a,"SID",this.B);g.Yj(a,"CI",this.tB?"0":"1");g.Yj(a,"AID",this.Ns);F7(this,a);if(!g.Cc||g.uc(10))g.Yj(a,"TYPE","xmlhttp"),s7(this.Ie,a,!0,this.Yx,!1);else{g.Yj(a,"TYPE","html");var b=this.Ie,c=!!this.Yx;b.It=3;b.Um=O6(a.clone());wTa(b,c)}};
g.k.PM=function(a,b){if(0!=this.i&&(this.Ie==a||this.Vg==a))if(this.Zj=a.Au,this.Vg==a&&3==this.i)if(7<this.qp){try{var c=this.D.parse(b)}catch(d){c=null}if(Array.isArray(c)&&3==c.length)if(a=c,0==a[0])a:{if(!this.Fl){if(this.Ie)if(this.Ie.ut+3E3<this.Vg.ut)H7(this),this.Ie.cancel(),this.Ie=null;else break a;J7(this);q7(19)}}else this.wL=a[1],0<this.wL-this.Ns&&37500>a[2]&&this.tB&&0==this.Mr&&!this.Ap&&(this.Ap=o7((0,g.E)(this.UT,this),6E3));else K7(this,11)}else null!=b&&K7(this,11);else if(this.Ie==
a&&H7(this),!g.jb(b))for(a=this.D.parse(b),b=0;b<a.length;b++)c=a[b],this.Ns=c[0],c=c[1],2==this.i?"c"==c[0]?(this.B=c[1],this.Yx=c[2],c=c[3],null!=c?this.qp=c:this.qp=6,this.i=3,this.Mf&&this.Mf.yJ(),this.gJ=B7(this,this.nx()?this.Yx:null,this.nC),NTa(this)):"stop"==c[0]&&K7(this,7):3==this.i&&("stop"==c[0]?K7(this,7):"noop"!=c[0]&&this.Mf&&this.Mf.xJ(c),this.Mr=0)};
g.k.UT=function(){null!=this.Ap&&(this.Ap=null,this.Ie.cancel(),this.Ie=null,J7(this),q7(20))};
g.k.Xx=function(a){if(this.Ie==a){H7(this);this.Ie=null;var b=2}else if(this.Vg==a)this.Vg=null,b=1;else return;this.Zj=a.Au;if(0!=this.i)if(a.Fm)if(1==b){b=Date.now()-a.ut;var c=p7;c.dispatchEvent(new DTa(c,a.xq?a.xq.length:0,b,this.ls));G7(this);this.C.length=0}else NTa(this);else{c=a.getLastError();var d;if(!(d=3==c||7==c||0==c&&0<this.Zj)){if(d=1==b)this.Vg||this.vn||1==this.i||2<=this.ls?d=!1:(this.vn=o7((0,g.E)(this.UM,this,a),OTa(this,this.ls)),this.ls++,d=!0);d=!(d||2==b&&J7(this))}if(d)switch(c){case 1:K7(this,
5);break;case 4:K7(this,10);break;case 3:K7(this,6);break;case 7:K7(this,12);break;default:K7(this,2)}}};
g.k.OR=function(a){if(!g.Pb(arguments,this.i))throw Error("Unexpected channel state: "+this.i);};
g.k.AX=function(a){a?q7(2):(q7(1),PTa(this,8))};
g.k.pD=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Di;a.S=!1;return a};
g.k.isActive=function(){return!!this.Mf&&this.Mf.isActive(this)};
g.k.Aj=function(a){var b=p7;b.dispatchEvent(new ETa(b,a))};
g.k.nx=function(){return!(!g.Cc||g.uc(10))};
g.k=QTa.prototype;g.k.yJ=function(){};
g.k.xJ=function(){};
g.k.wJ=function(){};
g.k.cD=function(){};
g.k.jK=function(){return{}};
g.k.isActive=function(){return!0};g.k=RTa.prototype;g.k.isEmpty=function(){return 0===this.i.length&&0===this.u.length};
g.k.clear=function(){this.i=[];this.u=[]};
g.k.contains=function(a){return g.Pb(this.i,a)||g.Pb(this.u,a)};
g.k.remove=function(a){var b=this.i;var c=(0,g.WMa)(b,a);0<=c?(g.Tb(b,c),b=!0):b=!1;return b||g.Ub(this.u,a)};
g.k.Op=function(){for(var a=[],b=this.i.length-1;0<=b;--b)a.push(this.i[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(L7,g.H);g.k=L7.prototype;g.k.hW=function(){this.Sf=Math.min(3E5,2*this.Sf);this.B();this.u&&this.start()};
g.k.start=function(){var a=this.Sf+15E3*Math.random();g.Pq(this.i,a);this.u=Date.now()+a};
g.k.stop=function(){this.i.stop();this.u=0};
g.k.isActive=function(){return this.i.isActive()};
g.k.reset=function(){this.i.stop();this.Sf=5E3};g.Ta(M7,QTa);g.k=M7.prototype;g.k.subscribe=function(a,b,c){return this.B.subscribe(a,b,c)};
g.k.unsubscribe=function(a,b,c){return this.B.unsubscribe(a,b,c)};
g.k.ag=function(a){return this.B.ag(a)};
g.k.ea=function(a,b){return this.B.ea.apply(this.B,arguments)};
g.k.dispose=function(){this.ma||(this.ma=!0,g.fe(this.B),UTa(this),g.fe(this.u),this.u=null,this.Z=function(){return""})};
g.k.isDisposed=function(){return this.ma};
g.k.connect=function(a,b,c){if(!this.i||2!=this.i.getState()){this.X="";this.u.stop();this.D=a||null;this.C=b||0;a=this.va+"/test";b=this.va+"/bind";var d=new E7(c?c.firstTestResults:null,c?c.secondTestResults:null,this.Aa),e=this.i;e&&(e.Mf=null);d.Mf=this;this.i=d;N7(this);if(this.i){d=g.O("ID_TOKEN");var f=this.i.Yj||{};d?f["x-youtube-identity-token"]=d:delete f["x-youtube-identity-token"];this.i.Yj=f}e?(3!=e.getState()&&0==KTa(e)||e.getState(),this.i.connect(a,b,this.I,e.B,e.Ns)):c?this.i.connect(a,
b,this.I,c.sessionId,c.arrayId):this.i.connect(a,b,this.I)}};
g.k.sendMessage=function(a,b){a={_sc:a};b&&g.Me(a,b);this.u.isActive()||2==(this.i?this.i.getState():0)?this.K.push(a):O7(this)&&(N7(this),JTa(this.i,a))};
g.k.yJ=function(){this.u.reset();this.D=null;this.C=0;if(this.K.length){var a=this.K;this.K=[];for(var b=0,c=a.length;b<c;++b)JTa(this.i,a[b])}this.ea("handlerOpened")};
g.k.wJ=function(a){var b=2==a&&401==this.i.Zj;4==a||b||this.u.start();this.ea("handlerError",a,b)};
g.k.cD=function(a){if(!this.u.isActive())this.ea("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.K.push(d)}};
g.k.jK=function(){var a={v:2};this.X&&(a.gsessionid=this.X);0!=this.C&&(a.ui=""+this.C);0!=this.S&&(a.ui=""+this.S);this.D&&g.Me(a,this.D);return a};
g.k.xJ=function(a){"S"==a[0]?this.X=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),HTa(this.i)):this.ea("handlerMessage",new STa(a[0],a[1]))};
g.k.XA=function(a){(this.I.loungeIdToken=a)||this.u.stop();if(this.Ba&&this.i){var b=this.i.Yj||{};a?b["X-YouTube-LoungeId-Token"]=a:delete b["X-YouTube-LoungeId-Token"];this.i.Yj=b}};
g.k.eX=function(){this.u.isActive();0==KTa(this.i)&&this.connect(this.D,this.C)};P7.prototype.C=function(a,b,c,d){b?a(d):a({text:c.responseText})};
P7.prototype.B=function(a,b){a(Error("Request error: "+b.status))};
P7.prototype.D=function(a){a(Error("request timed out"))};var aUa=Date.now(),S7=null,V7=Array(50),U7=-1,W7=!1;g.Ta(X7,g.Zx);X7.prototype.Ih=function(){return this.screens};
X7.prototype.contains=function(a){return!!Z6(this.screens,a)};
X7.prototype.get=function(a){return a?$6(this.screens,a):null};
X7.prototype.info=function(a){T7(this.I,a)};g.w(Y7,g.Zx);g.k=Y7.prototype;g.k.start=function(){!this.i&&isNaN(this.Mb)&&this.gN()};
g.k.stop=function(){this.i&&(this.i.abort(),this.i=null);isNaN(this.Mb)||(g.ht(this.Mb),this.Mb=NaN)};
g.k.xa=function(){this.stop();g.Zx.prototype.xa.call(this)};
g.k.gN=function(){this.Mb=NaN;this.i=g.Kt(Q7(this.B,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:this.K},timeout:5E3,onSuccess:(0,g.E)(this.zQ,this),onError:(0,g.E)(this.yQ,this),onTimeout:(0,g.E)(this.AQ,this)})};
g.k.zQ=function(a,b){this.i=null;a=b.screen||{};a.dialId=this.C;a.name=this.I;b=-1;this.D&&a.shortLivedLoungeToken&&a.shortLivedLoungeToken.value&&a.shortLivedLoungeToken.refreshIntervalMs&&(a.screenIdType="shortLived",a.loungeToken=a.shortLivedLoungeToken.value,b=a.shortLivedLoungeToken.refreshIntervalMs);this.ea("pairingComplete",new U6(a),b)};
g.k.yQ=function(a){this.i=null;a.status&&404==a.status?this.u>=uVa.length?this.ea("pairingFailed",Error("DIAL polling timed out")):(a=uVa[this.u],this.Mb=g.ft((0,g.E)(this.gN,this),a),this.u++):this.ea("pairingFailed",Error("Server error "+a.status))};
g.k.AQ=function(){this.i=null;this.ea("pairingFailed",Error("Server not responding"))};
var uVa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta($7,X7);g.k=$7.prototype;g.k.start=function(){Z7(this)&&this.ea("screenChange");!g.Ny("yt-remote-lounge-token-expiration")&&eUa(this);g.ht(this.i);this.i=g.ft((0,g.E)(this.start,this),1E4)};
g.k.add=function(a,b){Z7(this);bUa(this,a);a8(this,!1);this.ea("screenChange");b(a);a.token||eUa(this)};
g.k.remove=function(a,b){var c=Z7(this);dUa(this,a)&&(a8(this,!1),c=!0);b(a);c&&this.ea("screenChange")};
g.k.rB=function(a,b,c,d){var e=Z7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,a8(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.ea("screenChange")};
g.k.xa=function(){g.ht(this.i);$7.ke.xa.call(this)};
g.k.mS=function(a){Z7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}a8(this,!b);b&&T7(this.I,"Missed "+b+" lounge tokens.")};
g.k.lS=function(a){T7(this.I,"Requesting lounge tokens failed: "+a)};g.w(c8,g.Zx);g.k=c8.prototype;g.k.start=function(){var a=parseInt(g.Ny("yt-remote-fast-check-period")||"0",10);(this.C=g.Sa()-144E5<a?0:a)?f8(this):(this.C=g.Sa()+3E5,g.My("yt-remote-fast-check-period",this.C),this.XF())};
g.k.isEmpty=function(){return g.Fe(this.i)};
g.k.update=function(){b8("Updating availability on schedule.");var a=this.I(),b=g.re(this.i,function(c,d){return c&&!!$6(a,d)},this);
e8(this,b)};
g.k.xa=function(){g.ht(this.B);this.B=NaN;this.u&&(this.u.abort(),this.u=null);g.Zx.prototype.xa.call(this)};
g.k.XF=function(){g.ht(this.B);this.B=NaN;this.u&&this.u.abort();var a=gUa(this);if(Q6(a)){var b=Q7(this.D,"/pairing/get_screen_availability");this.u=R7(this.D,b,{lounge_token:g.ye(a).join(",")},(0,g.E)(this.OV,this,a),(0,g.E)(this.NV,this))}else e8(this,{}),f8(this)};
g.k.OV=function(a,b){this.u=null;var c=g.ye(gUa(this));if(g.ic(c,g.ye(a))){b=b.screens||[];c={};for(var d=0,e=b.length;d<e;++d)c[a[b[d].loungeToken]]="online"==b[d].status;e8(this,c);f8(this)}else this.le("Changing Screen set during request."),this.XF()};
g.k.NV=function(a){this.le("Screen availability failed: "+a);this.u=null;f8(this)};
g.k.le=function(a){T7("OnlineScreenService",a)};g.Ta(g8,X7);g.k=g8.prototype;g.k.start=function(){this.u.start();this.i.start();this.screens.length&&(this.ea("screenChange"),this.i.isEmpty()||this.ea("onlineScreenChange"))};
g.k.add=function(a,b,c){this.u.add(a,b,c)};
g.k.remove=function(a,b,c){this.u.remove(a,b,c);this.i.update()};
g.k.rB=function(a,b,c,d){this.u.contains(a)?this.u.rB(a,b,c,d):(a="Updating name of unknown screen: "+a.name,T7(this.I,a),d(Error(a)))};
g.k.Ih=function(a){return a?this.screens:g.Wb(this.screens,g.No(this.B,function(b){return!this.contains(b)},this))};
g.k.gI=function(){return g.No(this.Ih(!0),function(a){return!!this.i.i[a.id]},this)};
g.k.hI=function(a,b,c,d,e,f){var h=this;this.info("getDialScreenByPairingCode "+a+" / "+b);var l=new Y7(this.C,a,b,c,d);l.subscribe("pairingComplete",function(m,n){g.fe(l);e(h8(h,m),n)});
l.subscribe("pairingFailed",function(m){g.fe(l);f(m)});
l.start();return(0,g.E)(l.stop,l)};
g.k.BQ=function(a,b,c,d){g.Kt(Q7(this.C,"/pairing/get_screen"),{method:"POST",postParams:{pairing_code:a},timeout:5E3,onSuccess:(0,g.E)(function(e,f){e=new U6(f.screen||{});if(!e.name||kUa(this,e.name)){a:{f=e.name;for(var h=2,l=b(f,h);kUa(this,l);){h++;if(20<h)break a;l=b(f,h)}f=l}e.name=f}c(h8(this,e))},this),
onError:(0,g.E)(function(e){d(Error("pairing request failed: "+e.status))},this),
onTimeout:(0,g.E)(function(){d(Error("pairing request timed out."))},this)})};
g.k.xa=function(){g.fe(this.u);g.fe(this.i);g8.ke.xa.call(this)};
g.k.vS=function(){mUa(this);this.ea("screenChange");this.i.update()};
g8.prototype.dispose=g8.prototype.dispose;g.Ta(j8,g.Zx);g.k=j8.prototype;g.k.getScreen=function(){return this.C};
g.k.yg=function(a){this.isDisposed()||(a&&(l8(this,""+a),this.ea("sessionFailed")),this.C=null,this.ea("sessionScreen",null))};
g.k.info=function(a){T7(this.Ba,a)};
g.k.iI=function(){return null};
g.k.mG=function(a){var b=this.i;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.E)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.E)(function(){l8(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.k.xa=function(){this.mG("");j8.ke.xa.call(this)};g.w(m8,j8);g.k=m8.prototype;g.k.lG=function(a){if(this.u){if(this.u==a)return;l8(this,"Overriding cast session with new session object");vUa(this);this.va=!1;this.X="unknown";this.u.removeUpdateListener(this.Z);this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa)}this.u=a;this.u.addUpdateListener(this.Z);this.u.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa);rUa(this,"getMdxSessionStatus")};
g.k.Os=function(a){this.info("launchWithParams no-op for Cast: "+g.bi(a))};
g.k.stop=function(){this.u?this.u.stop((0,g.E)(function(){this.yg()},this),(0,g.E)(function(){this.yg(Error("Failed to stop receiver app."))},this)):this.yg(Error("Stopping cast device without session."))};
g.k.mG=function(){};
g.k.xa=function(){this.info("disposeInternal");vUa(this);this.u&&(this.u.removeUpdateListener(this.Z),this.u.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.Aa));this.u=null;j8.prototype.xa.call(this)};
g.k.DW=function(a,b){if(!this.isDisposed())if(b)if(b=R6(b),g.La(b))switch(a=""+b.type,b=b.data||{},this.info("onYoutubeMessage_: "+a+" "+g.bi(b)),a){case "mdxSessionStatus":pUa(this,b);break;case "loungeToken":sUa(this,b);break;default:l8(this,"Unknown youtube message: "+a)}else l8(this,"Unable to parse message.");else l8(this,"No data in message.")};
g.k.xK=function(a,b,c,d){g.ht(this.S);this.S=0;jUa(this.B,this.i.label,a,this.i.friendlyName,(0,g.E)(function(e){e?b(e):0<=d?(l8(this,"Screen "+a+" appears to be offline. "+d+" retries left."),this.S=g.ft((0,g.E)(this.xK,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.k.iI=function(){return this.u};
g.k.CQ=function(a){this.isDisposed()||a||(l8(this,"Cast session died."),this.yg())};g.w(p8,j8);g.k=p8.prototype;g.k.lG=function(a){this.u=a;this.u.addUpdateListener(this.Ia)};
g.k.Os=function(a){this.Ka=a;this.ma()};
g.k.stop=function(){CUa(this);this.u?this.u.stop((0,g.E)(this.yg,this,null),(0,g.E)(this.yg,this,"Failed to stop DIAL device.")):this.yg()};
g.k.xa=function(){CUa(this);this.u&&this.u.removeUpdateListener(this.Ia);this.u=null;j8.prototype.xa.call(this)};
g.k.DQ=function(a){this.isDisposed()||a||(l8(this,"DIAL session died."),this.D(),this.D=g.Ha,this.yg())};g.w(t8,j8);t8.prototype.stop=function(){this.yg()};
t8.prototype.lG=function(){};
t8.prototype.Os=function(){g.ht(this.u);this.u=NaN;var a=$6(this.B.Ih(),this.i.label);a?k8(this,a):this.yg(Error("No such screen"))};
t8.prototype.xa=function(){g.ht(this.u);this.u=NaN;j8.prototype.xa.call(this)};g.w(u8,g.Zx);g.k=u8.prototype;
g.k.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.S,[chrome.cast.Capability.AUDIO_OUT]);this.X||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED;a=a||this.I?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION;var e=(0,g.E)(this.xV,this);c=new chrome.cast.ApiConfig(c,(0,g.E)(this.QM,this),e,d,a);c.customDialLaunchCallback=(0,g.E)(this.rU,this);
chrome.cast.initialize(c,(0,g.E)(function(){this.isDisposed()||(chrome.cast.addReceiverActionListener(this.D),YTa(),this.u.subscribe("onlineScreenChange",(0,g.E)(this.jI,this)),this.B=FUa(this),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(f){this.le("Failed to set initial custom receivers: "+g.bi(f))},this)),this.ea("yt-remote-cast2-availability-change",w8(this)),b(!0))},this),(0,g.E)(function(f){this.le("Failed to initialize API: "+g.bi(f));
b(!1)},this))};
g.k.jX=function(a,b){v8("Setting connected screen ID: "+a+" -> "+b);if(this.i){var c=this.i.getScreen();if(!a||c&&c.id!=a)v8("Unsetting old screen status: "+this.i.i.friendlyName),x8(this,null)}if(a&&b){if(!this.i){c=$6(this.u.Ih(),a);if(!c){v8("setConnectedScreenStatus: Unknown screen.");return}if("shortLived"==c.idType){v8("setConnectedScreenStatus: Screen with id type to be short lived.");return}a=DUa(this,c);a||(v8("setConnectedScreenStatus: Connected receiver not custom..."),a=new chrome.cast.Receiver(c.uuid?
c.uuid:c.id,c.name),a.receiverType=chrome.cast.ReceiverType.CUSTOM,this.B.push(a),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(d){this.le("Failed to set initial custom receivers: "+g.bi(d))},this)));
v8("setConnectedScreenStatus: new active receiver: "+a.friendlyName);x8(this,new t8(this.u,a),!0)}this.i.mG(b)}else v8("setConnectedScreenStatus: no screen.")};
g.k.kX=function(a){this.isDisposed()?this.le("Setting connection data on disposed cast v2"):this.i?this.i.Os(a):this.le("Setting connection data without a session")};
g.k.FQ=function(){this.isDisposed()?this.le("Stopping session on disposed cast v2"):this.i?(this.i.stop(),x8(this,null)):v8("Stopping non-existing session")};
g.k.requestSession=function(){chrome.cast.requestSession((0,g.E)(this.QM,this),(0,g.E)(this.RV,this))};
g.k.xa=function(){this.u.unsubscribe("onlineScreenChange",(0,g.E)(this.jI,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.D);var a=VTa,b=g.Ga("yt.mdx.remote.debug.handlers_");g.Ub(b||[],a);g.fe(this.i);g.Zx.prototype.xa.call(this)};
g.k.le=function(a){T7("Controller",a)};
g.k.SM=function(a,b){this.i==a&&(b||x8(this,null),this.ea("yt-remote-cast2-session-change",b))};
g.k.uV=function(a,b){if(!this.isDisposed())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),v8("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.i)if(this.i.i.label!=a.label)v8("onReceiverAction_: Stopping active receiver: "+this.i.i.friendlyName),this.i.stop();else{v8("onReceiverAction_: Casting to active receiver.");this.i.getScreen()&&this.ea("yt-remote-cast2-session-change",this.i.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:x8(this,
new t8(this.u,a));break;case chrome.cast.ReceiverType.DIAL:x8(this,new p8(this.u,a,this.C,this.config_));break;case chrome.cast.ReceiverType.CAST:x8(this,new m8(this.u,a,this.config_));break;default:this.le("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.i&&this.i.i.label==a.label?this.i.stop():this.le("Stopping receiver w/o session: "+a.friendlyName)}else this.le("onReceiverAction_ called without receiver.")};
g.k.rU=function(a){if(this.isDisposed())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.le("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.i?this.i.i:null;if(!c||c.label!=b.label)return this.le("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.i.getScreen())return v8("Reselecting dial screen."),
this.ea("yt-remote-cast2-session-change",this.i.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.le('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x8(this,new p8(this.u,b,this.C,this.config_))}b=this.i;b.S=a;b.S.appState==chrome.cast.DialAppState.RUNNING?(a=b.S.extraData||{},c=a.screenId||null,q8(b)&&a.loungeToken?a.loungeTokenRefreshIntervalMs?a=zUa(b,{name:b.i.friendlyName,screenId:a.screenId,loungeToken:a.loungeToken,dialId:b.S.receiver.label,
screenIdType:"shortLived"},a.loungeTokenRefreshIntervalMs):(g.Ls(Error("No loungeTokenRefreshIntervalMs presents in additionalData: "+JSON.stringify(a)+".")),a=AUa(b,c)):a=AUa(b,c)):a=s8(b);return a};
g.k.QM=function(a){var b=this;if(!this.isDisposed()&&!this.I){v8("New cast session ID: "+a.sessionId);var c=a.receiver;if(c.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.i)if(c.receiverType==chrome.cast.ReceiverType.CAST)v8("Got resumed cast session before resumed mdx connection."),c.friendlyName=chrome.cast.unescape(c.friendlyName),x8(this,new m8(this.u,c,this.config_),!0);else{this.le("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var d=this.i.i,e=$6(this.u.Ih(),
d.label);e&&V6(e,c.label)&&d.receiverType!=chrome.cast.ReceiverType.CAST&&c.receiverType==chrome.cast.ReceiverType.CAST&&(v8("onSessionEstablished_: manual to cast session change "+c.friendlyName),g.fe(this.i),this.i=new m8(this.u,c,this.config_),this.i.subscribe("sessionScreen",(0,g.E)(this.SM,this,this.i)),this.i.subscribe("sessionFailed",function(){return EUa(b,b.i)}),this.i.Os(null));
this.i.lG(a)}}};
g.k.EQ=function(){return this.i?this.i.iI():null};
g.k.RV=function(a){this.isDisposed()||(this.le("Failed to estabilish a session: "+g.bi(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&x8(this,null),this.ea("yt-remote-cast2-session-failed"))};
g.k.xV=function(a){v8("Receiver availability updated: "+a);if(!this.isDisposed()){var b=w8(this);this.K=a==chrome.cast.ReceiverAvailability.AVAILABLE;w8(this)!=b&&this.ea("yt-remote-cast2-availability-change",w8(this))}};
g.k.jI=function(){this.isDisposed()||(this.B=FUa(this),v8("Updating custom receivers: "+g.bi(this.B)),chrome.cast.setCustomReceivers(this.B,g.Ha,(0,g.E)(function(){this.le("Failed to set custom receivers.")},this)),this.ea("yt-remote-cast2-availability-change",w8(this)))};
u8.prototype.setLaunchParams=u8.prototype.kX;u8.prototype.setConnectedScreenStatus=u8.prototype.jX;u8.prototype.stopSession=u8.prototype.FQ;u8.prototype.getCastSession=u8.prototype.EQ;u8.prototype.requestSession=u8.prototype.requestSession;u8.prototype.init=u8.prototype.init;u8.prototype.dispose=u8.prototype.dispose;var D8=[];g.k=I8.prototype;
g.k.reset=function(a){this.listId="";this.index=-1;this.videoId="";J8(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.trackData=a.trackData,this.Hk=a.hasPrevious,this.hasNext=a.hasNext,this.K=a.playerTime,this.I=a.playerTimeAt,this.C=a.seekableStart,this.i=a.seekableEnd,this.D=a.duration,this.S=a.loadedTime,this.B=a.liveIngestionTime,this.u=
!isNaN(this.B))};
g.k.Ec=function(){return 1==this.playerState};
g.k.isAdPlaying=function(){return 1081==this.playerState};
g.k.Lj=function(a){this.D=isNaN(a)?0:a};
g.k.getDuration=function(){return this.u?this.D+K8(this):this.D};
g.k.clone=function(){return new I8(O8(this))};g.w(Q8,g.Zx);g.k=Q8.prototype;g.k.getState=function(){return this.B};
g.k.play=function(){S8(this)?(this.i?this.i.play(null,g.Ha,X8(this,"play")):W8(this,"play"),V8(this,1,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.play)};
g.k.pause=function(){S8(this)?(this.i?this.i.pause(null,g.Ha,X8(this,"pause")):W8(this,"pause"),V8(this,2,M8(R8(this))),this.ea("remotePlayerChange")):T8(this,this.pause)};
g.k.seekTo=function(a){if(S8(this)){if(this.i){var b=R8(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.Ec()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.i.seek(c,g.Ha,X8(this,"seekTo",{newTime:a}))}else W8(this,"seekTo",{newTime:a});V8(this,3,a);this.ea("remotePlayerChange")}else T8(this,g.Pa(this.seekTo,a))};
g.k.stop=function(){if(S8(this)){this.i?this.i.stop(null,g.Ha,X8(this,"stopVideo")):W8(this,"stopVideo");var a=R8(this);a.index=-1;a.videoId="";J8(a);U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.stop)};
g.k.setVolume=function(a,b){if(S8(this)){var c=R8(this);if(this.u){if(c.volume!=a){var d=Math.round(a)/100;this.u.setReceiverVolumeLevel(d,(0,g.E)(function(){T7("CP","set receiver volume: "+d)},this),(0,g.E)(function(){this.le("failed to set receiver volume.")},this))}c.muted!=b&&this.u.setReceiverMuted(b,(0,g.E)(function(){T7("CP","set receiver muted: "+b)},this),(0,g.E)(function(){this.le("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);W8(this,"setVolume",e)}c.muted=b;c.volume=a;U8(this,c)}else T8(this,g.Pa(this.setVolume,a,b))};
g.k.kI=function(a,b){if(S8(this)){var c=R8(this);a={videoId:a};b&&(c.trackData={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},a.style=g.bi(b.style),g.Me(a,c.trackData));W8(this,"setSubtitlesTrack",a);U8(this,c)}else T8(this,g.Pa(this.kI,a,b))};
g.k.setAudioTrack=function(a,b){S8(this)?(b=b.getLanguageInfo().getId(),W8(this,"setAudioTrack",{videoId:a,audioTrackId:b}),a=R8(this),a.audioTrackId=b,U8(this,a)):T8(this,g.Pa(this.setAudioTrack,a,b))};
g.k.playVideo=function(a,b,c,d,e,f,h){d=void 0===d?null:d;e=void 0===e?null:e;f=void 0===f?null:f;h=void 0===h?null:h;var l=R8(this),m={videoId:a};void 0!==c&&(m.currentIndex=c);N8(l,a,c||0);void 0!==b&&(L8(l,b),m.currentTime=b);d&&(m.listId=d);e&&(m.playerParams=e);f&&(m.clickTrackingParams=f);h&&(m.locationInfo=g.bi(h));W8(this,"setPlaylist",m);d||U8(this,l)};
g.k.EA=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"previous")}else T8(this,g.Pa(this.EA,a,b))};
g.k.nextVideo=function(a,b){if(S8(this)){if(a&&b){var c=R8(this);N8(c,a,b);U8(this,c)}W8(this,"next")}else T8(this,g.Pa(this.nextVideo,a,b))};
g.k.Qr=function(){if(S8(this)){W8(this,"clearPlaylist");var a=R8(this);a.reset();U8(this,a);this.ea("remotePlayerChange")}else T8(this,this.Qr)};
g.k.SJ=function(){S8(this)?W8(this,"dismissAutoplay"):T8(this,this.SJ)};
g.k.dispose=function(){if(3!=this.B){var a=this.B;this.B=3;this.ea("proxyStateChange",a,this.B)}g.Zx.prototype.dispose.call(this)};
g.k.xa=function(){RUa(this);this.C=null;this.D.clear();P8(this,null);g.Zx.prototype.xa.call(this)};
g.k.nG=function(a){if((a!=this.B||2==a)&&3!=this.B&&0!=a){var b=this.B;this.B=a;this.ea("proxyStateChange",b,a);if(1==a)for(;!this.D.isEmpty();)b=a=this.D,0===b.i.length&&(b.i=b.u,b.i.reverse(),b.u=[]),a.i.pop().apply(this);else 3==a&&this.dispose()}};
g.k.sV=function(a,b){this.ea(a,b)};
g.k.cU=function(a){if(!a)this.Bw(null),P8(this,null);else if(this.u.receiver.volume){a=this.u.receiver.volume;var b=R8(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)T7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,U8(this,b)}};
g.k.Bw=function(a){T7("CP","Cast media: "+!!a);this.i&&this.i.removeUpdateListener(this.S);if(this.i=a)this.i.addUpdateListener(this.S),SUa(this),this.ea("remotePlayerChange")};
g.k.bU=function(a){a?(SUa(this),this.ea("remotePlayerChange")):this.Bw(null)};
g.k.IG=function(){W8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.k.jU=function(){var a=OUa();a&&P8(this,a)};
g.k.le=function(a){T7("CP",a)};g.w(Y8,g.Zx);g.k=Y8.prototype;
g.k.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.videoIds,f=b.playerParams,h=b.clickTrackingParams,l=b.index,m={videoId:d},n=b.currentTime,p=b.locationInfo;b=b.loopMode;void 0!==n&&(m.currentTime=5>=n?0:n);f&&(m.playerParams=f);p&&(m.locationInfo=p);h&&(m.clickTrackingParams=h);c&&(m.listId=c);e&&0<e.length&&(m.videoIds=e.join(","));void 0!==l&&(m.currentIndex=l);this.Ba&&(m.loopMode=b||"LOOP_MODE_OFF");c&&(this.jc.listId=c);this.jc.videoId=d;this.jc.index=l||0;this.jc.state=3;L8(this.jc,
n);this.C="UNSUPPORTED";c=this.Ba?"setInitialState":"setPlaylist";Z8("Connecting with "+c+" and params: "+g.bi(m));this.i.connect({method:c,params:g.bi(m)},a,aTa())}else Z8("Connecting without params"),this.i.connect({},a,aTa());VUa(this)};
g.k.XA=function(a){this.i.XA(a)};
g.k.dispose=function(){this.isDisposed()||(g.Fa("yt.mdx.remote.remoteClient_",null,void 0),this.ea("beforeDispose"),$8(this,3));g.Zx.prototype.dispose.call(this)};
g.k.xa=function(){a9(this);c9(this);b9(this);g.ht(this.K);this.K=NaN;g.ht(this.S);this.S=NaN;this.B=null;g.Ju(this.X);this.X.length=0;this.i.dispose();g.Zx.prototype.xa.call(this);this.C=this.I=this.u=this.jc=this.i=null};
g.k.hS=function(){this.Zr(2)};
g.k.gU=function(){Z8("Channel opened");this.va&&(this.va=!1,b9(this),this.Z=g.ft((0,g.E)(function(){Z8("Timing out waiting for a screen.");this.Zr(1)},this),15E3));
eTa(TTa(this.i),this.Ka)};
g.k.dU=function(){Z8("Channel closed");isNaN(this.D)?e7(!0):e7();this.dispose()};
g.k.eU=function(a,b){e7();isNaN(this.Nv())?(b&&"shortLived"==this.Aa&&this.ea("browserChannelAuthError",a),Z8("Channel error: "+a+" without reconnection"),this.dispose()):(this.va=!0,Z8("Channel error: "+a+" with reconnection in "+this.Nv()+" ms"),$8(this,2))};
g.k.hL=function(a){if(!this.u||0===this.u.length)return!1;for(var b=g.r(this.u),c=b.next();!c.done;c=b.next())if(!c.value.capabilities.has(a))return!1;return!0};
g.k.fU=function(a){a.params?Z8("Received: action="+a.action+", params="+g.bi(a.params)):Z8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=R6(a.params.devices);this.u=g.um(a,function(c){return new T6(c)});
a=!!g.Mb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
YUa(this,a);a=this.hL("mlm");this.ea("multiStateLoopEnabled",a);break;case "loungeScreenDisconnected":g.Vb(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
YUa(this,!1);break;case "remoteConnected":var b=new T6(R6(a.params.device));g.Mb(this.u,function(c){return b?c.id==b.id:!1})||OSa(this.u,b);
break;case "remoteDisconnected":b=new T6(R6(a.params.device));g.Vb(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":$Ua(this,a);break;case "nowPlaying":bVa(this,a);break;case "onStateChange":aVa(this,a);break;case "onAdStateChange":cVa(this,a);break;case "onVolumeChanged":dVa(this,a);break;case "onSubtitlesTrackChanged":ZUa(this,a);break;case "nowAutoplaying":eVa(this,a);break;case "autoplayDismissed":this.ea("autoplayDismissed");break;case "autoplayUpNext":this.I=a.params.videoId||null;this.ea("autoplayUpNext",this.I);break;case "onAutoplayModeChanged":this.C=
a.params.autoplayMode;this.ea("autoplayModeChange",this.C);"DISABLED"==this.C&&this.ea("autoplayDismissed");break;case "onHasPreviousNextChanged":fVa(this,a);break;case "requestAssistedSignIn":this.ea("assistedSignInRequested",a.params.authCode);break;case "onLoopModeChanged":this.ea("loopModeChange",a.params.loopMode);break;default:Z8("Unrecognized action: "+a.action)}};
g.k.XW=function(){if(this.B){var a=this.B;this.B=null;this.jc.videoId!=a&&d9(this,"getNowPlaying")}};
g.k.dS=function(){var a=3;this.isDisposed()||(a=0,isNaN(this.Nv())?O7(this.i)&&isNaN(this.D)&&(a=1):a=2);return a};
g.k.Zr=function(a){Z8("Disconnecting with "+a);g.Fa("yt.mdx.remote.remoteClient_",null,void 0);a9(this);this.ea("beforeDisconnect",a);1==a&&e7();UTa(this.i,a);this.dispose()};
g.k.bS=function(){var a=this.jc;this.B&&(a=this.jc.clone(),N8(a,this.B,a.index));return O8(a)};
g.k.lX=function(a){var b=new I8(a);b.videoId&&b.videoId!=this.jc.videoId&&(this.B=b.videoId,g.ht(this.K),this.K=g.ft((0,g.E)(this.XW,this),5E3));var c=[];this.jc.listId==b.listId&&this.jc.videoId==b.videoId&&this.jc.index==b.index||c.push("remoteQueueChange");this.jc.playerState==b.playerState&&this.jc.volume==b.volume&&this.jc.muted==b.muted&&M8(this.jc)==M8(b)&&g.bi(this.jc.trackData)==g.bi(b.trackData)||c.push("remotePlayerChange");this.jc.reset(a);g.kc(c,function(d){this.ea(d)},this)};
g.k.wK=function(){var a=this.i.I.id,b=g.Mb(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.k.Nv=function(){var a=this.i;return a.u.isActive()?a.u.u-Date.now():NaN};
g.k.YR=function(){return this.C||"UNSUPPORTED"};
g.k.ZR=function(){return this.I||""};
g.k.GQ=function(){if(!isNaN(this.Nv())){var a=this.i.u;g.Qq(a.i);a.start()}};
g.k.iX=function(a,b){d9(this,a,b);XUa(this)};
g.k.lI=function(){var a=g.Wt("SID","")||"",b=g.Wt("SAPISID","")||"",c=g.Wt("__Secure-3PAPISID","")||"";if(!a&&!b&&!c)return"";a=g.xc(g.db(a),2);b=g.xc(g.db(b),2);c=g.xc(g.db(c),2);return g.xc(g.db(a+","+b+","+c),2)};
Y8.prototype.subscribe=Y8.prototype.subscribe;Y8.prototype.unsubscribeByKey=Y8.prototype.ag;Y8.prototype.getProxyState=Y8.prototype.dS;Y8.prototype.disconnect=Y8.prototype.Zr;Y8.prototype.getPlayerContextData=Y8.prototype.bS;Y8.prototype.setPlayerContextData=Y8.prototype.lX;Y8.prototype.getOtherConnectedRemoteId=Y8.prototype.wK;Y8.prototype.getReconnectTimeout=Y8.prototype.Nv;Y8.prototype.getAutoplayMode=Y8.prototype.YR;Y8.prototype.getAutoplayVideoId=Y8.prototype.ZR;Y8.prototype.reconnect=Y8.prototype.GQ;
Y8.prototype.sendMessage=Y8.prototype.iX;Y8.prototype.getXsrfToken=Y8.prototype.lI;Y8.prototype.isCapabilitySupportedOnConnectedDevices=Y8.prototype.hL;g.w(e9,X7);g.k=e9.prototype;g.k.Ih=function(a){return this.Re.$_gs(a)};
g.k.contains=function(a){return!!this.Re.$_c(a)};
g.k.get=function(a){return this.Re.$_g(a)};
g.k.start=function(){this.Re.$_st()};
g.k.add=function(a,b,c){this.Re.$_a(a,b,c)};
g.k.remove=function(a,b,c){this.Re.$_r(a,b,c)};
g.k.rB=function(a,b,c,d){this.Re.$_un(a,b,c,d)};
g.k.xa=function(){for(var a=0,b=this.i.length;a<b;++a)this.Re.$_ubk(this.i[a]);this.i.length=0;this.Re=null;X7.prototype.xa.call(this)};
g.k.HQ=function(){this.ea("screenChange")};
g.k.YU=function(){this.ea("onlineScreenChange")};
g8.prototype.$_st=g8.prototype.start;g8.prototype.$_gspc=g8.prototype.BQ;g8.prototype.$_gsppc=g8.prototype.hI;g8.prototype.$_c=g8.prototype.contains;g8.prototype.$_g=g8.prototype.get;g8.prototype.$_a=g8.prototype.add;g8.prototype.$_un=g8.prototype.rB;g8.prototype.$_r=g8.prototype.remove;g8.prototype.$_gs=g8.prototype.Ih;g8.prototype.$_gos=g8.prototype.gI;g8.prototype.$_s=g8.prototype.subscribe;g8.prototype.$_ubk=g8.prototype.ag;var r9=null,x9=!1,f9=null,g9=null,w9=null,k9=[];g.w(y9,g.H);g.k=y9.prototype;g.k.xa=function(){g.H.prototype.xa.call(this);this.i.stop();this.B.stop();this.S.stop();this.Z();var a=this.Ub;a.unsubscribe("proxyStateChange",this.OM,this);a.unsubscribe("remotePlayerChange",this.Fw,this);a.unsubscribe("remoteQueueChange",this.qA,this);a.unsubscribe("previousNextChange",this.KM,this);a.unsubscribe("nowAutoplaying",this.EM,this);a.unsubscribe("autoplayDismissed",this.hM,this);this.Ub=this.u=null};
g.k.qj=function(a){var b=g.za.apply(1,arguments);if(2!=this.Ub.B)if(z9(this)){var c=a;if(!R8(this.Ub).isAdPlaying()||"control_seek"!==c)switch(c){case "control_toggle_play_pause":R8(this.Ub).Ec()?this.Ub.pause():this.Ub.play();break;case "control_play":this.Ub.play();break;case "control_pause":this.Ub.pause();break;case "control_seek":this.K.fI(b[0],b[1]);break;case "control_subtitles_set_track":A9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":b=
this.J.getCurrentTime();B9(this,0===b?void 0:b);break;case "control_seek":B9(this,b[0]);break;case "control_subtitles_set_track":A9(this,b[0]);break;case "control_set_audio_track":this.setAudioTrack(b[0])}};
g.k.ZT=function(a){this.S.vQ(a)};
g.k.RX=function(a){this.qj("control_subtitles_set_track",g.Fe(a)?null:a)};
g.k.gO=function(){var a=this.J.getOption("captions","track");g.Fe(a)||A9(this,a)};
g.k.Yb=function(a){this.u.Yb(a,this.J.getVideoData().lengthSeconds)};
g.k.JU=function(){g.Fe(this.C)||qVa(this,this.C);this.D=!1};
g.k.OM=function(a,b){this.B.stop();2===b&&this.aO()};
g.k.Fw=function(){if(z9(this)){this.i.stop();var a=R8(this.Ub);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.u.tf=1;break;case 1082:case 1083:this.u.tf=0;break;default:this.u.tf=-1}switch(a.playerState){case 1081:case 1:this.Vb(new g.MJ(8));this.ZN();break;case 1085:case 3:this.Vb(new g.MJ(9));break;case 1083:case 0:this.Vb(new g.MJ(2));this.K.stop();this.Yb(this.J.getVideoData().lengthSeconds);break;case 1084:this.Vb(new g.MJ(4));break;case 2:this.Vb(new g.MJ(4));this.Yb(M8(a));
break;case -1:this.Vb(new g.MJ(64));break;case -1E3:this.Vb(new g.MJ(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo no se puede reproducir de forma remota."}))}a=R8(this.Ub).trackData;var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.C=a,qVa(this,a));a=R8(this.Ub);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.X.isActive()||this.IO()}else pVa(this)};
g.k.KM=function(){this.J.ea("mdxpreviousnextchange")};
g.k.qA=function(){z9(this)||pVa(this)};
g.k.EM=function(a){isNaN(a)||this.J.ea("mdxnowautoplaying",a)};
g.k.hM=function(){this.J.ea("mdxautoplaycanceled")};
g.k.setAudioTrack=function(a){z9(this)&&this.Ub.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.k.seekTo=function(a,b){-1===R8(this.Ub).playerState?B9(this,a):b&&this.Ub.seekTo(a)};
g.k.IO=function(){var a=this;if(z9(this)){var b=R8(this.Ub);this.events.kc(this.ma);b.muted?this.J.mute():this.J.unMute();this.J.setVolume(b.volume);this.ma=this.events.T(this.J,"onVolumeChange",function(c){oVa(a,c)})}};
g.k.ZN=function(){this.i.stop();if(!this.Ub.isDisposed()){var a=R8(this.Ub);a.Ec()&&this.Vb(new g.MJ(8));this.Yb(M8(a));this.i.start()}};
g.k.aO=function(){this.B.stop();this.i.stop();var a=this.Ub.C.getReconnectTimeout();2==this.Ub.B&&!isNaN(a)&&this.B.start()};
g.k.Vb=function(a){this.B.stop();var b=this.I;if(!g.RJ(b,a)){var c=g.U(a,2);c!==g.U(this.I,2)&&this.J.At(c);this.I=a;sVa(this.u,b,a)}};g.w(C9,g.W);C9.prototype.xd=function(){this.i.show()};
C9.prototype.Fb=function(){this.i.hide()};
C9.prototype.u=function(){S6("mdx-privacy-popup-cancel");this.Fb()};
C9.prototype.B=function(){S6("mdx-privacy-popup-confirm");this.Fb()};g.w(D9,g.W);D9.prototype.onStateChange=function(a){rVa(this,a.state)};g.w(E9,g.LP);E9.prototype.D=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.Bo=g.lc(a,this.i,this),g.MP(this,g.um(a,this.i)),a=this.J.getOption("remote","currentReceiver"),a=this.i(a),this.options[a]&&this.Xh(a),this.enable(!0)):this.enable(!1)};
E9.prototype.i=function(a){return a.key};
E9.prototype.hj=function(a){return"cast-selector-receiver"===a?"Reparto...":this.Bo[a].name};
E9.prototype.Af=function(a){g.LP.prototype.Af.call(this,a);this.J.setOption("remote","currentReceiver",this.Bo[a]);this.Bb.Fb()};g.w(F9,g.VM);g.k=F9.prototype;
g.k.create=function(){var a=this.player.V(),b=g.QE(a);a={device:"Desktop",app:"youtube-desktop",loadCastApiSetupScript:a.N("mdx_load_cast_api_bootstrap_script"),enableDialLoungeToken:a.N("enable_dial_short_lived_lounge_token"),enableCastLoungeToken:a.N("enable_cast_short_lived_lounge_token")};jVa(b,a);this.subscriptions.push(g.ov("yt-remote-before-disconnect",this.XT,this));this.subscriptions.push(g.ov("yt-remote-connection-change",this.yV,this));this.subscriptions.push(g.ov("yt-remote-receiver-availability-change",this.MM,
this));this.subscriptions.push(g.ov("yt-remote-auto-connect",this.wV,this));this.subscriptions.push(g.ov("yt-remote-receiver-resumed",this.vV,this));this.subscriptions.push(g.ov("mdx-privacy-popup-confirm",this.MW,this));this.subscriptions.push(g.ov("mdx-privacy-popup-cancel",this.LW,this));this.MM()};
g.k.load=function(){this.player.cancelPlayback();g.VM.prototype.load.call(this);this.di=new y9(this,this.player,this.Ub);var a=(a=nVa())?a.currentTime:0;var b=v9()?new Q8(p9(),void 0):null;0==a&&b&&(a=M8(R8(b)));0!==a&&this.Yb(a);sVa(this,this.yd,this.yd);this.player.Yk(6)};
g.k.unload=function(){this.player.ea("mdxautoplaycanceled");this.cn=this.Ok;(0,g.ge)(this.di,this.Ub);this.Ub=this.di=null;g.VM.prototype.unload.call(this);this.player.Yk(5);G9(this)};
g.k.xa=function(){g.pv(this.subscriptions);g.VM.prototype.xa.call(this)};
g.k.Qk=function(a){var b=g.za.apply(1,arguments);this.loaded&&this.di.qj.apply(this.di,[a].concat(g.v(b)))};
g.k.getAdState=function(){return this.tf};
g.k.Hk=function(){return this.Ub?R8(this.Ub).Hk:!1};
g.k.hasNext=function(){return this.Ub?R8(this.Ub).hasNext:!1};
g.k.Yb=function(a,b){this.xL=a||0;this.player.ea("progresssync",a,b);this.player.Ma("onVideoProgress",a||0)};
g.k.getCurrentTime=function(){return this.xL};
g.k.getProgressState=function(){var a=R8(this.Ub),b=this.player.getVideoData();return{airingStart:0,airingEnd:0,allowSeeking:this.player.V().N("web_player_mdx_allow_seeking_change_killswitch")?this.player.qf():!a.isAdPlaying()&&this.player.qf(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.u?a.B+K8(a):a.B,isAtLiveHead:1>=(a.u?a.i+K8(a):a.i)-this.getCurrentTime(),loaded:a.S,seekableEnd:a.u?a.i+K8(a):a.i,seekableStart:0<
a.C?a.C+K8(a):a.C}};
g.k.nextVideo=function(){this.Ub&&this.Ub.nextVideo()};
g.k.EA=function(){this.Ub&&this.Ub.EA()};
g.k.XT=function(a){1===a&&(this.KF=this.Ub?R8(this.Ub):null)};
g.k.yV=function(){var a=v9()?new Q8(p9(),void 0):null;if(a){var b=this.cn;this.loaded&&this.unload();this.Ub=a;this.KF=null;b.key!==this.Ok.key&&(this.cn=b,this.load())}else(0,g.fe)(this.Ub),this.Ub=null,this.loaded&&(this.unload(),(a=this.KF)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,M8(a)));this.player.ea("videodatachange","newdata",this.player.getVideoData(),3)};
g.k.MM=function(){var a=[this.Ok],b=a.concat,c=kVa();E8()&&g.Ny("yt-remote-cast-available")&&c.push({key:"cast-selector-receiver",name:"Cast..."});this.Bo=b.call(a,c);a=q9()||this.Ok;H9(this,a);this.player.Ma("onMdxReceiversChange")};
g.k.wV=function(){var a=q9();H9(this,a)};
g.k.vV=function(){this.cn=q9()};
g.k.MW=function(){this.Ow=!0;G9(this);x9=!1;r9&&t9(r9,1);r9=null};
g.k.LW=function(){this.Ow=!1;G9(this);H9(this,this.Ok);this.cn=this.Ok;x9=!1;r9=null;this.player.playVideo()};
g.k.hf=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.Bo;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?G8():H9(this,b)),this.loaded?this.cn:this.Ok;case "quickCast":return 2===this.Bo.length&&"cast-selector-receiver"===this.Bo[1].key?(b&&G8(),!0):!1}};
g.k.IG=function(){this.Ub.IG()};
g.k.Li=function(){return!1};
g.k.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.UM("remote",F9);})(_yt_player);
